extra states cobrand feature
mysociety/fixmystreet pull request #3164
Opened 2020-08-21 13:14 UTC by struan

This allows display strings for a state/external status combination to be configured as a cobrand feature.

For mysociety/fixmystreet-commercial#1952

[skip changelog]

2020-08-28 11:25 UTC, davea requested changes
Sneaky little crash in there, otherwise looks good.

2020-08-28 11:25 UTC, davea commented on perllib/FixMyStreet/Cobrand/FixMyStreet.pm
> +    $state = $cfg->{$state}->{$code} || $state;
This was crashing with `Modification of a read-only value attempted` if `$cfg->{$state}` was undef, so something like this is needed:

```suggestion
    $state = ( $cfg->{$state}->{$code} || $state ) if $cfg->{$state};
```

2020-08-28 11:25 UTC, davea commented on perllib/FixMyStreet/Cobrand/UKCouncils.pm
> +    $state = $cfg->{$state}->{$code} || $state;
Same as above in `FixMyStreet.pm`.

2020-09-10 13:31 UTC, struan commented
merged in https://github.com/mysociety/fixmystreet/commit/342e235b916696da4ef7982885cefe0f8b069adf

2020-09-10 13:31 UTC, closed without merging