[Oxfordshire] Hide duplicate ‘Other’ category from map filters
mysociety/fixmystreet pull request #3169
Opened 2020-08-25 14:48 UTC by davea

Two rows would be returned because the district and county `Other` contacts have different `extra` fields, so this adds a `WHERE` for the Oxfordshire cobrand to only fetch the county contact.

This probably isn't the best way to fix the problem.

[skip changelog]

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1964

2020-08-25 15:01 UTC, dracos requested changes
" This probably isn't the best way to fix the problem." - in fact this may make it worse elsewhere as you're now splitting up rows with the same category+extra but different bodies into multiple rows.

::My looks to have the same issue. (Reports is okay, as only one body.)

Really, the code here in Around and My should be de-duplicating. It looks like the only reason extra is fetched is so optional help text can be shown (on KiitC, and there's no interface for it), so a small loop that just takes the first of a particular category and drops subsequent of the same would do?

2020-08-25 16:04 UTC, davea commented
Yep, that's a better idea. Hopefully e51c372e83b19efdc08bfd03a841a86dc2661f45 does the trick.

2020-08-25 16:22 UTC, dracos approved these changes
It'd be good to have a test, though :)

2020-08-26 09:54 UTC, davea commented
Test added in ffe7f1bbfe91062d0f4dad076c4823e30102eeb6 - does that look OK?

2020-08-26 10:15 UTC, dracos commented
Looks good!

2020-08-28 11:38 UTC, merged