[TfL] barebones initial script
mysociety/fixmystreet pull request #3176
Opened 2020-09-10 13:51 UTC by struan

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1955

[skip changelog]

2020-09-17 08:16 UTC, dracos requested changes

2020-09-17 09:43 UTC, struan commented on perllib/FixMyStreet/Script/TfL/AutoClose.pm
> +        having => \[ 'MIN(comments.confirmed) < ?', $dtf->format_datetime($self->newest) ]
I had originally just used the lastupdate of the problem which is problematic in the other direction.

fetching all the the updates does seem like the only way to resolve this though. I guess with this query as the basis then at least you are only considering reports where there is a chance that they are valid so it's not too awful.

2020-09-18 11:13 UTC, dracos requested changes
Something odd happening in the tests, now they're running - failing sometimes, I think the test is assuming the order it will get a result in or something like that. Other than that, only one debug and one suggestion :)

2020-09-18 11:13 UTC, dracos commented on perllib/FixMyStreet/Script/TfL/AutoClose.pm
> +            warn $c->problem_state . "\n";
Debug

2020-09-18 11:13 UTC, dracos commented on perllib/FixMyStreet/Script/TfL/AutoClose.pm
> +        next unless defined $earliest && $earliest < $self->newest;
newest could be a lazy has attribute, so that it's only calculated once?

2020-09-21 11:49 UTC, dracos approved these changes
Looks good; one query about why something that I think is always set is a Maybe is all :)

2020-09-21 11:49 UTC, dracos commented on perllib/FixMyStreet/Script/TfL/AutoClose.pm
> +    isa => Maybe[InstanceOf['DateTime']],
Why Maybe, isn't it always a DateTime? :)

2020-10-14 09:41 UTC, merged