Societyworks demo cobrand
mysociety/fixmystreet pull request #3192
Opened 2020-09-23 16:44 UTC by zarino

**To do**

- [x] Reband Borsetshire cobrand as SocietyWorks Showcase
- [ ] Decide what to do about the bottom half of the homepage
- [ ] Decide whether / how the cobrand should link to societyworks.org
- [ ] Confirm which map type it’s best to use (time to switch from Google Maps?)
- [ ] Check whether there are any other recent features that need enabling in this cobrand (eg: assets) and whether they require any front-end changes
- [ ] Implement styling for `/waste` features

2020-09-23 16:46 UTC, dracos commented
"time to switch from Google Maps" - demo site uses OSM.

2020-09-23 16:57 UTC, zarino commented
> "time to switch from Google Maps" - demo site uses OSM.

Oh, so it does! I saw [google_maps_style.js](https://github.com/mysociety/fixmystreet/blob/e2fd716/web/cobrands/borsetshire/google_maps_style.js) in the borsetshire assets directory, and assumed it must still be using Google Maps… but, maybe that file isn’t even needed any more?

2020-09-28 13:29 UTC, LouiseMySociety commented
Spoke to Zarino about progress and what's needed next. Made this related ticket https://github.com/mysociety/fixmystreet-commercial/issues/2009

2020-10-19 10:51 UTC, dracos requested changes
Looks good, couple of issues.

2020-10-19 10:51 UTC, dracos commented on templates/web/base/alert/index.html
>    <a href="/alert/list" id="geolocate_link">&hellip; [% loc('or use my location') %]</a>
Should this line be removed then?

2020-10-19 10:51 UTC, dracos commented on templates/web/borsetshire/around/postcode_form.html
> -                <input type="text" name="_pc" value="[% pc | html %]" id="pc" size="10" maxlength="200" aria-describedby="pc-hint" required>
This functionality of a hidden pc and _pc for what they enter (so it always takes them to the pins) has been lost, could we have it back?

2020-10-19 10:51 UTC, dracos commented on perllib/FixMyStreet/Cobrand/Borsetshire.pm
> +    my $uprn = shift;
Would be good to have some tests for all this, I can add some basic ones.

2020-10-22 15:56 UTC, dracos commented
Going to deploy on this branch for now, and won't be merged into that branch now after tidying, so closing this but is deployed.

2020-10-22 15:56 UTC, closed without merging