[Noise] ask directly for location rather than if know it
mysociety/fixmystreet pull request #3210
Opened 2020-10-08 13:27 UTC by struan

Instead of having a separate flow for known/unknown location have a
location search box and then show a list of addresses if they enter a
Hackney postcode, or the map page if we can't get a list of addresses.

For https://github.com/mysociety/fixmystreet-commercial/issues/2013

[skip changelog]

2020-10-09 15:44 UTC, dracos requested changes
Some bugs to fix, looks like, but yes, I think this is a clearer flow.
I guess test didn't pick up the postcode submission bug because it always returns results even if given new data, could return nothing in that case.

2020-10-09 15:44 UTC, dracos commented on t/app/controller/noise.t
> +        $mech->submit_form_ok({ with_fields => { where => 'residence', source_location => 'A street' } });
This could be a location with multiple results, to show that that works (it currently does not), to be the reverse of the other test.

2020-10-09 15:44 UTC, dracos commented on perllib/FixMyStreet/App/Form/Noise.pm
> -has_field source_postcode => (
You've removed this, fine, but the source_known_address page still uses it to do the lookup if need be. So e.g. entering a Hackney postcode as source, pick one of the results, hit submit, currently get an error "'200002791497' is not a valid value" as it's not looked them up.

2020-10-09 15:44 UTC, dracos commented on perllib/FixMyStreet/App/Form/Noise.pm
> +    post_process => sub {
process is always called on a form, both on 'arrival' and submission, so this goes a bit odd when possible_location_matches is the list, and not the single result, putting "ARRAY" in lat and null in lon. Guess it doesn't matter as is overwritten on next page, but wonder if there was a cleaner way. I used Amhurst Road as my test location.

2020-10-23 11:20 UTC, dracos requested changes
This works well apart from one scenario, sorry - if you enter a source address (not a postcode) and go through that flow and then go back to there (or earlier) in the flow, when you get back to the address entry and don't change anything, it resets and you have to pick a place (if multiple locations) and pick from the map again. It should remember the location and keep using it if you haven't changed the search text, I guess.

(Postcode works okay I think because the uprn is still stored in the `source_address` saved data and so your choice is still selected when you go to that page.)

(You'll have to mock out the address lookup for future dev as it's currently down.)

2020-10-28 12:01 UTC, struan commented
I'm not sure I understand what the issue is. I think this does the correct thing:


![Screen Recording 2020-10-28 at 11 50 16 2020-10-28 11_59_27](https://user-images.githubusercontent.com/5310/97433293-2cb50300-1915-11eb-8c4c-5af841415c6c.gif)

OTOH, it does seem that if you go back and enter a postcode it ignores that so I will fix that.

2020-11-02 12:06 UTC, dracos commented
Sorry I wasn't clear. "I'm not sure I understand what the issue is. I think this does the correct thing:" - if you moved the pin on the pin page, and then went back and clicked through (doesn't need to be a multiple-result search), the pin resets to the location result of the search result, not where you've subsequently placed the pin.

2020-11-09 18:03 UTC, dracos requested changes
Afraid it still doesn't work properly, sorry. Three examples:
1. Enter Danby House. Pin on Danby House, in the right place. Pick an area size, click Go, get error that I haven't given a latitude or longitude.
2. Enter Well Street. Pick first result. Click "search for a different location". Enter Danby House (which has 1 result). Pin is still on Well Street, not Danby House.
3. Enter Danby House. Pin on Danby House. Click "search for a different location". Enter Well Street. Get taken straight to map, no disambiguation page, pin still on Danby House.

Feels like this is more complex than it needs to be. I sort of see the point of the source_lat/lon fields, but are they necessary? If it had its previous behaviour of storing lat/lon on one result, or chosen result, and if someone goes back and has a new search value in source_location or pc, that clears the values, is that not enough? When do you need to maintain the lat/lon if they've searched for a new search term? I may have missed something.

Could the `pc` field be dropped and that page reuse the `source_location` field? I know the postcode behaviour is different, but if that helps simplify it I don't think it would matter much.

2020-11-11 10:40 UTC, struan commented
Only thing I'm not sure on is at the moment if you put in an address that requires disambiguation, e.g Hackney Marshes, then on re-editing you don't get an option to change that, which I'm not sure is the right decision.

2020-11-11 10:48 UTC, dracos commented
Oh yes, I see what you mean; though you can click Back from the map page easily enough rather than "Search for a new location" I guess. But if you get to the end, then go back to edit, you mean. Hmm. How about if you always go to `source_known_address` or `choose_location` from `where` page, never straight to `map` (and presumably if you haven't changed the text your choice on `choose_location` will be remembered from `location_matches` field?) and then only if the `location_matches` changes would you delete lat/lon and lose the previous location. Does that work?

2020-11-11 13:53 UTC, struan commented
Ok, tweaked that.

2020-11-11 15:05 UTC, dracos requested changes
🎉 Sorry for all the issues, but looks like it's all good now. One tidy up I think. And the PR test implies might need bit of hand-holding to merge okay.

2020-11-11 15:05 UTC, dracos commented on perllib/FixMyStreet/App/Form/Noise.pm
> +            if ( !$saved_data->{latitude} && !$saved_data->{longitude} ) {
This if block can just be removed I think, the same stuff happens underneath.

2020-11-12 13:03 UTC, dracos approved these changes
📣 📣

2020-11-12 13:43 UTC, merged