Increase affordance on map buttons on mobile when making a new report
mysociety/fixmystreet pull request #3214
Opened 2020-10-12 09:39 UTC by wrightmartin

This pull request makes a visual change to the buttons to chose the location on the map on mobile (see screenshots)
- Increase affordance (they look like buttons now)
- Increase visibility (the yellow prevents the next action more visible)

Before
![image](https://user-images.githubusercontent.com/2292925/95731153-0fc2d380-0c77-11eb-8e93-0d9d8adf8a34.png)

After
![image](https://user-images.githubusercontent.com/2292925/95731187-16e9e180-0c77-11eb-8132-aec244661a2d.png)

Please check the following:

- [x] Whether this PR should include changes to any documentation, or the FAQ;
- [x] All cobrand-specific commits start their commit message with the cobrand in square brackets;
- [x] Is new functionality tested? CodeCov will warn you about the diff coverage, but won’t complain about e.g. new files;
- [x] Are the changes tested for accessibility?
- [ ] Have you updated the changelog? If this is not necessary, put square brackets around this: skip changelog

Please check the contributing docs, and describe your pull request here.
Screenshots or GIF animations (using e.g. LICEcap) may be helpful.

Please include any issues that are fixed, using "fixes" or "closes" so that
they are auto-closed when the PR is merged.

Thanks for contributing!

2020-10-15 09:02 UTC, dracos reviewed
Any reason this was only on the .com cobrand, and not all cobrands? If it looks better on one, it's hopefully better on all :) Only because otherwise I find we don't find the time to broaden these things out.

2020-10-15 09:10 UTC, dracos requested changes
When you click Continue, map_ok becomes a different button that takes you back up to the map. The changes here change this a bit - e.g. line spacing reduces, it goes bold, don't know if that's wanted or not, or if worth splitting this out to be a different class/done differently as part of this.

2021-05-04 08:42 UTC, zarino requested changes
Generally looks good.

Back button looks a bit weird on TfL:

<img width="413" alt="Screenshot 2021-05-04 at 09 15 49" src="https://user-images.githubusercontent.com/739624/116978582-d22da280-acbb-11eb-95b6-9e0fc2a8b058.png">

And on Highways England:

<img width="411" alt="Screenshot 2021-05-04 at 09 38 30" src="https://user-images.githubusercontent.com/739624/116979133-84656a00-acbc-11eb-9c59-5c954e79aaff.png">


Primary button on some cobrands doesn’t have good text contrast, eg Northamptonshire:

<img width="402" alt="Screenshot 2021-05-04 at 09 33 31" src="https://user-images.githubusercontent.com/739624/116978621-e07bbe80-acbb-11eb-8985-70dca8246456.png">

Peterborough:

<img width="409" alt="Screenshot 2021-05-04 at 09 35 50" src="https://user-images.githubusercontent.com/739624/116978830-25075a00-acbc-11eb-8230-9ff054cf6f32.png">

Lots of weirdness going on with Hackney:

<img width="414" alt="Screenshot 2021-05-04 at 09 39 43" src="https://user-images.githubusercontent.com/739624/116979264-b1b21800-acbc-11eb-982e-4f5f63171977.png">

2026-05-01 16:43 UTC, dracos commented
No-one appears to have really minded and it's been 5 years.

2026-05-01 16:43 UTC, closed without merging