[CheshireEast] allow cleaning reports to be made anywhere
mysociety/fixmystreet pull request #3232
Opened 2020-11-02 14:33 UTC by struan

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2050

[skip changelog]

2020-11-10 17:34 UTC, dracos requested changes
Looks fine. I guess one question (presumably considered) is that if the highways layer now doesn't apply to all categories, why not list the categories it does apply to and stop it being `all_categories`, instead of providing an exemption list? Is that list much longer?

2020-11-10 17:34 UTC, dracos commented on web/cobrands/cheshireeast/assets.js
> +          console.log(cat, cleaning_cats);
debug

2020-11-10 17:34 UTC, dracos commented on web/cobrands/cheshireeast/assets.js
> +              fixmystreet.message_controller.road_found();
Should perhaps pass layer in (though I realise not used)?

2020-11-11 16:05 UTC, struan commented
The list of categories it applies to is much longer so this seemed the sensible way round.

2020-11-11 16:17 UTC, dracos approved these changes

2021-04-15 09:26 UTC, merged