[Bexley] replace notice urls with staff specific ones
mysociety/fixmystreet pull request #3243
Opened 2020-11-13 18:36 UTC by struan

For some categories Bexley staff use a different URL from the public in
the notices. This allows the public URL in the notice to be replaced.

[skip changelog]

2020-11-13 18:37 UTC, struan commented
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/2060

2020-11-16 09:28 UTC, dracos requested changes
Assuming the test failure is only due to the debugging left in, looks fine :)

2020-11-16 09:28 UTC, dracos commented on perllib/FixMyStreet/Cobrand/Bexley.pm
> +                    use Data::Printer;
debugging :)

2020-11-16 13:38 UTC, dracos approved these changes

2020-12-01 12:10 UTC, merged