Bromley waste phase2 payments
mysociety/fixmystreet pull request #3336
Opened 2021-03-04 12:23 UTC by struan

2021-03-25 18:08 UTC, dracos requested changes
This is a big PR, which has made it hard (and long) to look through, perhaps e.g. the caching could have been a separate PR, the renewal form bit, etc? (I realise they were separate commits, which definitely helped and I looked through them individually but e.g. waste_sub_due was used in a commit before it was defined.) I'm not sure I have managed to check or have caught everything, but I'm afraid there's quite a lot of comments nevertheless.

2021-03-25 18:08 UTC, dracos commented on t/app/controller/waste.t
> +    subtest 'check new sub credit card payment lookup failed' => sub {
This and next test seem identical apart from the mock - refactor? Also, they're testing what the code does but I'm not sure that's a great outcome for the user at present

2021-03-25 18:08 UTC, dracos commented on perllib/FixMyStreet/Cobrand/Bromley.pm
> +    return $self->feature('payment_gateway')->{ggw_cost} * $bin_count;
There are a number of places that make this calculation and don't use this function.

2021-03-25 18:08 UTC, dracos commented on perllib/FixMyStreet/App/Controller/Waste.pm
> +    $c->set_param('service_id', $c->stash->{services_available}->{Garden_Waste}->{service_id});
There's the special garden ID function?

2021-03-25 18:08 UTC, dracos commented on perllib/FixMyStreet/App/Form/Waste/Garden/Renew.pm
> +has_field billing_address => (
Can this share code with the garden subscription form, if all these fields are the same?

2021-03-26 16:54 UTC, struan commented on perllib/FixMyStreet/App/Controller/Waste.pm
> +            $c->forward('direct_debit_cancel_sub');
All the direct debit processing takes place in a separate process which I've not written yet which will do the confirming etc.

2021-03-26 17:08 UTC, struan commented on perllib/FixMyStreet/App/Controller/Waste.pm
> +        payer_reference => 1, # XXX
That's another thing that's being set up in the DD processing so it's awaiting that code before I know what's going on with it.

2021-03-30 16:37 UTC, struan commented on perllib/FixMyStreet/App/Controller/Waste.pm
>  sub pay_complete : Path('pay_complete') : Args(1) {
There isn't a hook option with the card payment API we're using.

2021-04-01 10:14 UTC, struan commented on perllib/FixMyStreet/App/Controller/Waste.pm
> +        extra => { like => '%property_id,T5:value,I_:'. $c->stash->{property}{id} . '%' }
I think the state is going to come from Echo as we're going to store the payment method in there so this code needs to change to reflect that. However I'm waiting on Echo being updated with that at the moment.

2021-04-01 11:10 UTC, struan commented on perllib/FixMyStreet/App/Controller/Waste.pm
>          # retry if in progress, error if invalid ref.
I'm going to fix this in the branch that fixes the card payments

2021-04-01 11:10 UTC, struan commented on perllib/FixMyStreet/App/Controller/Waste.pm
>              # cancelled, not attempted, logged out - try again option
I'm going to fix this in the branch that fixes the card payments

2021-04-07 16:32 UTC, dracos requested changes
Great, looks like everything I raised has been sorted. Only issue is I suggest the return URL is pay_complete/ID/random_token which lets you look it up quickly rather than scan, and is more random.

2021-04-07 18:02 UTC, dracos approved these changes
One typo in the test I think is all :)

2021-04-07 18:02 UTC, dracos commented on t/app/controller/waste.t
> +        $mech->get("/waste/dd_complete?reference=NOTATOKENreport_id=$report_id");
Should there be an `&` here?

2021-04-08 08:44 UTC, merged