[Oxfordshire] Replace contact form with a link to OCC's own form
mysociety/fixmystreet pull request #3446
Opened 2021-05-24 14:34 UTC by chrismytton

Oxfordshire have requested that the contact form be replaced with a link to their own form.

Fixes https://github.com/mysociety/societyworks/issues/2374

![image](https://user-images.githubusercontent.com/22996/119363243-7e541f00-bca5-11eb-972d-b390e7ce3cf1.png)

2021-05-24 15:12 UTC, struan approved these changes
✉️

2021-05-24 15:56 UTC, dracos requested changes
You cannot do this (exactly like this, I mean; sorry, was just replying quickly in case it got merged :) ), it breaks reporting abusive reports which uses the same template. Shouldn't be much more work to factor out the form part of the base template to its own file and then replace that with the link.

2021-05-25 08:21 UTC, chrismytton commented
@dracos Oooh good catch, thanks! Will factor the form out as you say.

2021-05-28 08:02 UTC, dracos approved these changes

2021-06-02 09:13 UTC, merged