Handle spaces in code names of extra data.
mysociety/fixmystreet pull request #3518
Opened 2021-07-02 17:12 UTC by ludovic-tc

An uncaught exception was being thrown by extra data which
included a space in the code (name), e.g. 'public safety',
when the user chose a report category.

+ **fixmystreet.js**: fix applied (single quotes around code name)
+ **fixture**: BathNES has new categories and extra data for testing
+ **bathnes.js**: additional Cypress test to trigger uncaught exception by clicking between road responsibility categories
+ **cypress.json**: fix to ensure Cypress tests run (is this appropriate?)

Fixes mysociety/fixmystreet#3308

Please check the following:

- [ ] Whether this PR should include changes to any documentation, or the FAQ;
- [ ] All cobrand-specific commits start their commit message with the cobrand in square brackets;
- [ ] Is new functionality tested? CodeCov will warn you about the diff coverage, but won’t complain about e.g. new files;
- [ ] Are the changes tested for accessibility?
- [ ] Have you updated the changelog? If this is not necessary, put square brackets around this: skip changelog

Please check the contributing docs, and describe your pull request here.
Screenshots or GIF animations (using e.g. LICEcap) may be helpful.

Please include any issues that are fixed, using "fixes" or "closes" so that
they are auto-closed when the PR is merged.

Thanks for contributing!

2021-07-02 17:24 UTC, ludovic-tc commented
@chrismytton NB: the test seems to break when it should work and vice versa! 🤦‍♂️

2021-07-05 08:58 UTC, dracos commented
The switch from blacklistHosts to blockHosts in the commit [1] breaks the tests on github because the version of cypress in the CI testing still uses blacklistHosts. So the tests running here were not blocking any external hosts and were calling those services because they were no longer blocked (you can see that e.g. in our tilma logs for requests from GitHub IPs at the time this occurred). If you drop that change, I'd hope the tests then pass (assuming that is the only issue).

[1] This shouldn't be in that commit anyway, because it is unrelated to the purpose of that commit.

2021-07-05 09:54 UTC, chrismytton requested changes
I think this is nearly there! Just a couple of comments.

2021-07-05 09:54 UTC, chrismytton commented on .cypress/cypress/integration/bathnes.js
> +    cy.visit('http://bathnes.localhost:3001/report/new?longitude=-2.368929&latitude=51.386969');
The lat/long that you've used here will need to be added to `t/Mock/MapIt.pm`, which is the mocked version of MapIt that's used in the tests.

You can see the lat/long that's used by the test above here:

https://github.com/mysociety/fixmystreet/blob/6f35c67e76ef8efdbca3d2e6fdec17d1625cabbd/t/Mock/MapIt.pm#L68

So I think you can basically duplicate that line and change the lat/long to the ones you're using here.

2021-07-05 09:54 UTC, chrismytton commented on .cypress/cypress.json
> +  "blockHosts": ["gaze.mysociety.org", "*.openstreetmap.org", "portal.roadworks.org", "tilma.mysociety.org", "tilma.staging.mysociety.org", "isharemaps.bathnes.gov.uk", "consent.cookiebot.com", "asse
As Matthew mentioned in another comment, you shouldn't need to change this if you're running cypress 3.x. As I mentioned in Slack I think you can get the appropriate versions installed with this command:

```
npm install -g cypress@3.8.3 @cypress/code-coverage@3.9.4 codecov
```

2021-07-05 09:56 UTC, chrismytton commented on .cypress/cypress/integration/bathnes.js
> +    cy.visit('http://bathnes.localhost:3001/report/new?longitude=-2.368929&latitude=51.386969');
Or alternatively you could re-use the same lat/long as the Curo test, think that would also work.

2021-07-05 16:42 UTC, chrismytton commented on .cypress/cypress/integration/bathnes.js
> +    cy.visit('http://bathnes.localhost:3001/report/new?longitude=-2.3659276latitude=51.379009');
There's a missing `&` between the two parameters in the URL. I think if you add that the tests should pass 🤞 

```suggestion
    cy.visit('http://bathnes.localhost:3001/report/new?longitude=-2.3659276&latitude=51.379009');
```

2021-08-12 12:01 UTC, chrismytton approved these changes
👾 

Let's have a chat about getting this deployed to production this afternoon 🚀

2021-08-12 15:24 UTC, merged