Stop sending UK Council questionairres if users can't update
mysociety/fixmystreet pull request #3534
Opened 2021-07-14 15:33 UTC by MorayMySoc

* There is a setting to not send questionnaires but this can be forgotten.
* If UK Council doesn't allow updates by users, don't send questionnaires.
* Adds method to test if users allowed to edit.
* Skips sending questionnaire if method returns true

2021-07-15 12:24 UTC, struan requested changes
There's a few cases which I think I missed explaining to handle, but this looks good otherwise.

2021-07-15 12:24 UTC, struan commented on t/cobrand/fixmystreet.t
> +};
I think these could all be covered by a loop rather than individual tests.

2021-07-15 12:24 UTC, struan commented on perllib/FixMyStreet/Cobrand/UKCouncils.pm
> +        return 1;
I should have mentioned this but we probably need to handle when updates_allowed is set to 'open' which means they can leave an update if the report is open but not if it's fixed or closed.

There's also a reporter-open and reporter settings, the first of which is probably relevant.

2021-07-15 12:24 UTC, struan commented on t/app/model/questionnaire.t
> +        user => 'user',
the setting for this is 'reporter' rather than user.

2021-07-22 13:54 UTC, struan requested changes
sorry, one tiny change I should have thought of earlier.

2021-07-22 13:54 UTC, struan commented on perllib/FixMyStreet/Cobrand/UKCouncils.pm
> +    my ($self, $is_open) = @_;
I wonder if passing in the row here and then doing the is_open check might be a bit more future proof

2021-07-22 16:41 UTC, struan requested changes
Code looks fine but few test issues.

2021-07-22 16:41 UTC, struan commented on t/cobrand/fixmystreet.t
> +        user_id      => 1,
This is causing the tests to fail as it needs a user. There's a `$mech->create_user_ok` method you can use to set one up and then use the id of the created user here.

2021-07-22 16:41 UTC, struan commented on t/cobrand/fixmystreet.t
> +        user_id      => 1,
Although actually it's probably easier to use `$mech->create_problems_for_body` to create the problem as it'll do most of the work.

2021-07-22 16:41 UTC, struan commented on t/cobrand/fixmystreet.t
> +        my $problem = FixMyStreet::DB->resultset('Problem')->create(
probably only need one problem for both these tests to save on repetition.

2021-07-23 13:05 UTC, struan commented on t/cobrand/fixmystreet.t
> +        user_id      => 1,
It probably works if you run them in isolation as it only creates the one user which will have Id 1 but when run as part of the suite it cleans out the database between tests which means the auto increment takes effect and the user created at the top of the script is no longer Id 1.

2021-07-23 13:31 UTC, struan approved these changes

2021-07-29 14:18 UTC, MorayMySoc commented
Merged and deployed

2021-07-29 14:18 UTC, closed without merging