Script to insert odour category to fixmystreet.com
mysociety/fixmystreet pull request #3537
Opened 2021-07-19 15:28 UTC by MorayMySoc

Add Environment Agency Odor category to FixMyStreet.com #2110

* Environment Agency would like odour issues in England to be emailed to them
* Model script on update_areas_covered
* Create Environment Agency body
* Add Odour category with dropdown and notes
* Add areas this applies to, to the new body

2021-07-20 14:21 UTC, struan requested changes
I've had a quick check and we're also going to need to stop this category appearing on cobrands. 

The categories to display are set up in https://github.com/mysociety/fixmystreet/blob/ae7bc51ef24f5960c71be65af391978ca23185b3/perllib/FixMyStreet/App/Controller/Report/New.pm#L732 so have a look at that and see if it makes sense.

2021-07-22 15:02 UTC, struan approved these changes
indenting still a bit off in the script but this looks good.

2021-07-22 15:02 UTC, struan commented on bin/fixmystreet.com/one-off-add-ics-body
> +$cat->insert;
Ah right, some of this is tabs and some is spaces is I think the problem. it should be spaces.

2021-07-29 14:17 UTC, MorayMySoc commented
Merged and released

2021-07-29 14:17 UTC, closed without merging