[Bromley] ask for the current bin count when modifying a subscription
mysociety/fixmystreet pull request #3541
Opened 2021-07-23 15:40 UTC by struan

Brings the modify screen in line with new and renew in asking for new bins.

Also refactors the renew/modify templates to reduce shared code.

Fixes mysociety/societyworks#2475

[skip changelog]

2021-08-12 12:05 UTC, dracos requested changes
Few small things

2021-08-12 12:05 UTC, dracos commented on templates/web/base/waste/garden/_bin_quantities.html
> +    <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
Can this template also be used in subscribe_details.html?

2021-08-17 15:50 UTC, dracos requested changes
Left in a debug line is all

2021-08-17 15:50 UTC, dracos commented on templates/web/base/waste/summary.html
> +    <form method="post" id="change_answers">
If you didn't want to add a special ID just for test and you know what `step1` is, I think submit_form_ok({ with_fields => { goto => [step1 value] } }) would also work.

2021-08-19 10:07 UTC, dracos approved these changes

2021-09-06 12:46 UTC, struan commented
This is awaiting someone at Bromley to test it before going live so I guess it might need a prod: https://mysocietysupport.freshdesk.com/a/tickets/1299

2021-09-20 13:13 UTC, merged