Adds language-pack-sv to install
mysociety/fixmystreet pull request #3546
Opened 2021-07-27 10:01 UTC by MorayMySoc

Swedish language pack should be part of install for tests to pass on linux #3544

This makes Swedish language pack part of the manual install for debian/ubuntu linux instructions.

2021-08-10 11:25 UTC, dracos requested changes
If this is to be added (and I see no reason not to, you're right, the tests should pass by default you would hope), I think we also need to add language-pack-de (at least, the automated tests add that one as well), and should probably add to packages.docker as well to maintain consistency there.

2021-08-10 11:29 UTC, MorayMySoc commented
Great - was about to get in touch to make sure this was worth pursuing and to say if so should add de too. I'll add that and have a look at the Docker file get the branch back up to date with master.

2021-08-13 10:00 UTC, dracos approved these changes
🇩🇪 🇸🇪

2021-08-16 10:11 UTC, MorayMySoc commented
Merged locally and pushed

2021-08-16 10:11 UTC, closed without merging