Add drain cover missing to tfl red route list
mysociety/fixmystreet pull request #3563
Opened 2021-08-05 16:00 UTC by MorayMySoc

Add an extra category to of "Drain cover missing" to tfl red route only list.

2021-08-06 11:14 UTC, davea requested changes
Going in the right direction! You'll also need to add the category to `tlrn_categories` in `web/cobrands/tfl/assets.js`.

One small point to note is that we generally prefix cobrand-/client-specific commit messages (as well as PR title) to make it obvious what they're for. In this case something like `[TfL] Add drain cover missing to red route list` would do. Please also include a link to the relevant ticket(s) so we can get more context about why a change has been made.

2021-08-06 11:24 UTC, MorayMySoc commented on perllib/FixMyStreet/Cobrand/TfL.pm
> +    "Drain cover missing",
I'm only seeing 'Bus stops' and 'Traffic lights' under deleted contacts for some reason. Will add text as in your note.

2021-08-06 11:34 UTC, MorayMySoc commented
[skip changelog]

2021-08-10 10:57 UTC, dracos approved these changes
🐉

2021-08-10 13:26 UTC, merged