WIP: [Bromley] Private comments for updates
mysociety/fixmystreet pull request #3584
Opened 2021-09-07 19:22 UTC by chrismytton

Fixes https://github.com/mysociety/societyworks/issues/2293

2021-09-13 10:07 UTC, dracos requested changes
One suggested tweak (plus Open311 test changes) is all :)

2021-09-14 08:35 UTC, chrismytton commented on t/cobrand/bromley.t
> +        $test_res->content('<?xml version="1.0" encoding="utf-8"?><service_request_updates><request_update><update_id>42</update_id></request_update></service_request_updates>');
Ooh yep, that should make this much simpler. I'll put this on staging once approved, but I'll update it to use the new method from #3588 once that's merged and get it re-reviewed.

2021-09-14 09:32 UTC, dracos approved these changes

2021-09-22 18:50 UTC, chrismytton commented on t/cobrand/bromley.t
> +        $test_res->content('<?xml version="1.0" encoding="utf-8"?><service_request_updates><request_update><update_id>42</update_id></request_update></service_request_updates>');
@dracos I've updated this to use the new Open311 testing bits now #3588 has been merged. Would you mind checking my fixup commit?

2021-09-23 08:02 UTC, dracos approved these changes
Looks good :) Phew that it did make it a bit simpler

2021-09-28 11:43 UTC, merged