[Oxfordshire] Send FMS ID to reporter in confirmation email.
mysociety/fixmystreet pull request #3699
Opened 2021-12-06 13:06 UTC by ludovic-tc

Add FMS ID to confirmation emails asking users to use it if they get in touch with the council. 

Please check the following:

- [x] All cobrand-specific commits start their commit message with the cobrand in square brackets;
- [x] Is new functionality tested? 
- [ ] Are the changes tested for accessibility?
[skip changelog]

Please check the contributing docs, and describe your pull request here.
Screenshots or GIF animations (using e.g. LICEcap) may be helpful.

Please include any issues that are fixed, using "fixes" or "closes" so that
they are auto-closed when the PR is merged.

Thanks for contributing!

2021-12-07 16:18 UTC, MorayMySoc approved these changes
Looks good to go

2022-01-20 14:49 UTC, dracos commented on templates/email/oxfordshire/problem-confirm.html
> +[%
Presumably this email template can now be dropped, given the user will be getting the subsequent email with the information contained in it?

2022-01-20 14:55 UTC, ludovic-tc commented on perllib/FixMyStreet/Cobrand/Oxfordshire.pm
> +sub report_sent_confirmation_email { 'external_id' }
Quite right. 🤦🏼

2022-01-20 15:23 UTC, dracos requested changes
The changes look fine, but you haven't updated the tests for your changes.

2022-01-24 16:58 UTC, dracos approved these changes
One superfluous line can be removed, looks fine otherwise.

2022-01-24 16:58 UTC, dracos commented on t/cobrand/oxfordshire.t
> +        my $email_subject = $mech->get_text_body_from_email($email);
This variable isn't used.

2022-01-26 17:05 UTC, dracos approved these changes

2022-01-27 13:50 UTC, dracos reviewed
Two other things to note, both git related:
* Please use --fixup or --squash for fixup commits rather than your own commit messages because a) we have code to prevent those commits being pushed to master, and b) it also makes it much easier for you to squash changes in because an interactive rebase will rearrange the commits for you if you set rebase.autosquash to true.
* "confirmation email" in FMS terms is the email sent to someone not logged in to confirm their report, not the logged email we (sometimes) send once the report is sent, and I realise the behaviour of this PR has changed, so do update your commit message when you come to squash these together.
Thanks.

2022-04-29 14:03 UTC, merged