[Shropshire] restrict phone numbers to non-text characters (0-9, +, space)
mysociety/fixmystreet pull request #3755
Opened 2022-01-19 11:19 UTC by ludovic-tc

Restrict phone numbers to non-text characters (0-9, +, space).
Shropshire have asked to be able to match:
+44 1234 567890
and similar phone numbers but not e.g. similar to the following which caused a stuck report:
`Customer - Mrs XXXX - 01746 222 222`
(Where the reporter was reporting on behalf of a resident.)

for https://mysocietysupport.freshdesk.com/a/tickets/1741

Please check the following:

- [ ] Whether this PR should include changes to any documentation, or the FAQ;
- [ ] All cobrand-specific commits start their commit message with the cobrand in square brackets;
- [ ] Is new functionality tested? CodeCov will warn you about the diff coverage, but won’t complain about e.g. new files;
- [ ] Will cobrand-specific changes require additional work to ensure consistent behaviour on www.fixmystreet.com? 🔍 
- [ ] Are the changes tested for accessibility?
- [ ] Have you updated the changelog? If this is not necessary, put square brackets around this: [skip changelog]

2022-02-08 19:01 UTC, dracos requested changes
Looks good, and good to see you got the test working 👍 
I've made a few requests to get it over the line, should be only a few minutes' work.

2022-02-09 11:17 UTC, ludovic-tc commented on .cypress/cypress/fixtures/highways-ajax.json
> +        "Flytipping":{"bodies":["Borsetshire", "Shropshire"]},
It wasn't testing, I thought this was required, but it's obvious now that it isn't (and should have been at the time). Also, the line was not meant to be duplicated.

2022-02-09 11:20 UTC, ludovic-tc commented on web/cobrands/fixmystreet-uk-councils/council_validation_rules.js
> +            required: true,
✅

2022-02-09 12:25 UTC, ludovic-tc commented on web/cobrands/fixmystreet-uk-councils/js.js
> +            phone_number.match( /^(?:(?:(?:00\s?|\+)44\s?)|(?:\(?0))(?:\d{2}\)?\s?\d{4}\s?\d{4}|\d{3}\)?\s?\d{3}\s?\d{3,4}|\d{4}\)?\s?(?:\d{5}|\d{3}\s?\d{3})|\d{5}\)?\s?\d{4,5})$/ );
Good spot!

2022-02-09 12:55 UTC, dracos commented on web/cobrands/fixmystreet-uk-councils/js.js
> +            phone_number.match( /^(?:(?:(?:00\s?|\+)44\s?)|(?:\(?0))(?:\d{2}\)?\s?\d{4}\s?\d{4}|\d{3}\)?\s?\d{3}\s?\d{3,4}|\d{4}\)?\s?(?:\d{5}|\d{3}\s?\d{3})|\d{5}\)?\s?\d{4,5})$/ );
Sorry that I wasn't clear - I don't think the solution for this was to stop removing spaces - we shouldn't care where people put spaces in their number. We should leave in the line stripping spaces etc, and then can remove any checking from spaces from the line I commented on.

2022-02-09 12:56 UTC, dracos requested changes
Thanks, just one thing to do where I don't think we want to not strip spaces and potentially annoy people who happen to put spaces in difference places.

2022-02-10 15:27 UTC, dracos requested changes
Sorry, but the UK has some phone numbers that are only 10 digits long (the old regex handled this). All I asked you to do was to remove the `\s?` (and `\(?`) from the regex. You didn't need to try and do more than that, or to test the "regex fairly extensively with a variety of real and generated UK phone numbers in separate JS (& Perl!) scripts", I'm afraid that was a waste of time. And now you have wasted more time because what you have ended up with won't actually work for some perfectly valid UK phone numbers. Please change the regex to my suggestion and then this can be done.

2022-02-10 16:19 UTC, ludovic-tc commented on web/cobrands/fixmystreet-uk-councils/js.js
> +            phone_number.match( /^(?:(?:(?:00|\+)44)|(?:0))[0-9]{10}$/ );
OK, I did want you to let me know whether you thought the regex was up to scratch, sorry it isn't.

2022-02-10 16:52 UTC, dracos approved these changes
Thanks for fixing the regex.

2022-03-11 11:38 UTC, merged