[Bristol] Adds bus stops to asset layer
mysociety/fixmystreet pull request #3762
Opened 2022-01-21 13:20 UTC by MorayMySoc

[skip changelog]

Bristol are adding bus stops to their assets layer.

https://github.com/mysociety/societyworks/issues/2774

2022-01-24 11:22 UTC, dracos requested changes
The group name doesn't look right, but other than that, assuming those are the right values to use, is fine

2022-01-24 11:22 UTC, dracos commented on web/cobrands/bristol/assets.js
> +    asset_group: "Bus stops",
The group is called "Bus Stops" in the staging admin

2022-01-24 11:54 UTC, dracos approved these changes

2022-02-01 16:59 UTC, closed without merging

2022-05-20 08:28 UTC, MorayMySoc commented
This is merged into Bristol-reviewed