[Merton] Updated Google Tag Manager container code to nonce-aware version
mysociety/fixmystreet pull request #3769
Opened 2022-01-31 21:00 UTC by ludovic-tc

cf. https://developers.google.com/tag-platform/tag-manager/web/csp

fixes https://mysocietysupport.freshdesk.com/a/tickets/1718
fixes mysociety/societyworks#2628

(hopefully!)

Please check the following:
- [x] ~Will cobrand-specific changes require additional work to ensure consistent behaviour on www.fixmystreet.com? 
- [ ] Are the changes tested for accessibility?
[skip changelog]

2022-02-01 09:15 UTC, dracos requested changes
The code has been copied and pasted without adjusting to use the correct ID.

2022-02-01 09:15 UTC, dracos commented on templates/web/merton/tracking_code.html
> +})(window,document,'script','dataLayer','GTM-XXXXXX');
This is the example ID.

2022-02-04 14:12 UTC, ludovic-tc commented on templates/web/merton/tracking_code.html
> +})(window,document,'script','dataLayer','GTM-XXXXXX');
Duh! Thank you... sorted

2022-02-04 17:03 UTC, dracos approved these changes

2022-02-04 18:25 UTC, merged