[WIP] Fix colour contrast issues in map page sidebar
mysociety/fixmystreet pull request #3794
Opened 2022-02-09 17:51 UTC by zarino

- [x] Lighten pagination element background colour (for mysociety/societyworks/#2844)
- [ ] Sort out "click map" styling (lots of cobrands hacking this their own way, should really be using `.fake-link`, if at all, maybe wording should also change to "use", instead of "see", across the board?)
- [ ] Changelog entry

2022-02-11 18:59 UTC, dracos requested changes
One typo, I think, also commit message says you're picking see instead of use :) (Also mix of curly/non-curly quotes in there given you're there anyway ;) )
Looks good, wish we'd done this ages ago!

2022-02-11 18:59 UTC, dracos commented on web/cobrands/oxfordshire/base.scss
> +.report-list-filterss-wrapper {
typo in the class name

2022-02-14 09:32 UTC, zarino commented
Thanks @dracos I can always trust you to pick me up on missing curly quotes. Serves me right for committing at 6pm!

Happy for me to merge?

2022-02-14 10:12 UTC, dracos approved these changes
🐍

2022-02-14 14:32 UTC, merged