[Peterborough] Replace '==' with 'eq' for memcached property check
mysociety/fixmystreet pull request #3796
Opened 2022-02-10 16:42 UTC by nephila-nacrea

Purely numerical check was not working for Peterborough as its
property IDs are of the form 'postcode:id_no'. So a string
equality check must be used instead.

Fixes https://mysocietysupport.freshdesk.com/a/tickets/1821.

[skip changelog]

2022-02-14 12:20 UTC, dracos requested changes
Looks good, couple of tiny suggestions is all :)

2022-02-14 12:20 UTC, dracos commented on t/app/controller/waste_peterborough.t
> +    $mech->log_in_ok('test@example.net');
I think it would be preferable to log_out_ok here (or in fact, up a few lines at the end of the SKIP inside which you logged in).

2022-02-14 12:20 UTC, dracos commented on t/app/controller/waste_peterborough.t
> +    my ($b) = shared_bartec_mocks();
Good solution :)

2022-02-14 12:20 UTC, dracos commented on t/app/controller/waste_peterborough.t
> +            $mech->get('/waste/PE1 3NA:100090215481');
If we make this 489 rather than 481, 489 is in the Bartec.pm sample_data and so we won't get some uninitialized warnings when running the tests.

2022-02-14 21:16 UTC, nephila-nacrea commented on t/app/controller/waste_peterborough.t
> +    my ($b) = shared_bartec_mocks();
Thank you ^.^

2022-02-15 11:27 UTC, dracos approved these changes
Looks good 🇬🇶

2022-02-15 12:38 UTC, merged