Added "Can’t use the map? Skip this step." to report problem here
mysociety/fixmystreet pull request #3847
Opened 2022-03-16 11:41 UTC by lucascumsille

This PR fixes the issue where users that are on /around page then click on "Report a problem here" on the navigation bar, and there wasn't a "Can’t use the map? Skip this step." button (same that we have implemented on /report/new) causing accessibility issues.

This has been implemented across all cobrands.

This fixes part of: mysociety/societyworks#2787

<img width="461" alt="Screenshot 2022-03-16 at 11 35 52" src="https://user-images.githubusercontent.com/13790153/158581650-0e2bdcf2-46ff-4373-a121-a0f0cc764e67.png">

Do I need to updated the changelog?

2022-03-16 11:43 UTC, dracos requested changes
As per the associated ticket description, could it be the middle option, not the top, and could it be only visible to screen readers and receives focus when using keyboard navigation, thanks.

2022-03-16 12:21 UTC, lucascumsille commented
@dracos  This latest commit would only allow screen reader and keyboard users to have access to skip map button.
Let me know if this solution is alright.
I thought about adding the "screen-reader-only" class, so we can reuse whenever we need something similar.

2022-03-16 12:50 UTC, dracos requested changes
Thanks, looking better - but would be good for it appear on focus similar to how `.map-alternatives` does, I guess?

2022-03-17 08:06 UTC, lucascumsille commented
> 
Thanks for the advice, Matthew
I just push a --fixup that does the same that `.map-alternatives`, but without all the extra styling.
I also added it to the list of elements that shouldn't be print out when printing the page.

2022-03-18 12:51 UTC, dracos approved these changes
Looks good; I've added setting the `url_skip` variable as if you go direct to /report/new rather than go via /around it would not have been set at the point the template was used.

2022-03-21 14:01 UTC, merged