[Cheshire East] Inspector tool amendments
mysociety/fixmystreet pull request #3862
Opened 2022-03-25 16:10 UTC by MorayMySoc

* Moves 'assignee' information on /admin/reports page into separate column
* Adds dropdown with list of assignees for filtering
* Includes filters 'Unassigned', 'All' and any assignees for the body
* Does not interact with search - search searches all reports unfiltered
* Adds tests to check functionality
* Adds test to check doesn't appear for another cobrand

https://github.com/mysociety/societyworks/issues/2777

[skip changelog]

2022-04-12 20:21 UTC, davea requested changes
Functionally this works great! But a few things to improve/tidy the code a little.

2022-04-12 20:21 UTC, davea commented on templates/web/base/admin/problem_row.html
> +            [% IF !c.cobrand.moniker == 'cheshireeast' %]
Similar to the Perl module, is there a way we can remove references to an individual cobrand here (and in the other template)? They're so enormous that you couldn't just override the entire template.

2022-06-07 15:31 UTC, nephila-nacrea requested changes

2024-09-06 07:00 UTC, dracos commented
Not going ahead

2024-09-06 07:00 UTC, closed without merging