[Buckinghamshire] Mark parish reports as internal referral after sending
mysociety/fixmystreet pull request #3993
Opened 2022-06-24 16:29 UTC by chrismytton

Adds a `post_report_sent` hook to Bucks which checks if any of the receiving bodies are a know Bucks parish and if so marks the report as internal referral.

Fixes https://github.com/mysociety/societyworks/issues/3075

[skip changelog]

2022-06-28 07:16 UTC, dracos requested changes

2022-06-28 07:16 UTC, dracos commented on perllib/FixMyStreet/Cobrand/FixMyStreet.pm
> +    my $bucks = FixMyStreet::Cobrand::Buckinghamshire->new;
Needed to create a new cobrand object here, as calling it directly with the FMS cobrand, it wouldn't have access to _parish_ids.

2022-06-28 07:16 UTC, dracos commented on perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
> +        if (grep $body_id, $self->_parish_ids) {
This needs to be `grep { $body_id == $_ } @{$self->_parish_ids}` - this is currently always matching as $body_id is always set.

2022-06-28 07:16 UTC, dracos commented on perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
> +    foreach my $body_id ($report->bodies_str_ids) {
This also needs `@{...}` around the arrayref, otherwise this loop is always called only once with $body_id set to the ref, not an ID.

2022-06-28 14:34 UTC, dracos commented on perllib/FixMyStreet/Cobrand/Buckinghamshire.pm
> +        if (grep $body_id, $self->_parish_ids) {
Oh, and we want parish_bodies, not _parish_ids which are the area IDs.

2022-07-11 17:04 UTC, chrismytton commented
@dracos Thanks for fixing my mistakes 🙂 This PR is still marked as changes requested, but I think the changes have been done now, is that right?

I ask because I'm looking to merge this into `bucks-parishes-reviewed` so everything is in one place.

2022-07-12 05:55 UTC, dracos commented
Yeah, I think I put it on staging but not in bucks-parishes-reviewed 👍

2022-07-13 10:31 UTC, merged