[Waste] Add cheque reference field.
mysociety/fixmystreet pull request #3998
Opened 2022-06-28 17:09 UTC by dracos

[skip changelog]

2022-06-29 09:22 UTC, struan requested changes
One small bug but otherwise this looks good.

Only other things is it might be an idea to list the cheque reference on the summary page?

2022-06-29 09:22 UTC, struan commented on templates/web/base/admin/reports/_edit_waste.html
>      [ 'Last payment method', 'LastPayMethod' ],
Unrelated to this but I notice that this just lists the number in the admin which I'm not sure is entirely helpful?

2022-06-29 10:13 UTC, dracos commented on web/js/waste.js
> +    if (id) { id.className += ' hidden-js'; }
Ah, it needs to run before the actual data-show/hide set up code (which does check which item is selected), hmm.

2022-07-05 11:27 UTC, struan approved these changes
👍

2022-07-05 11:45 UTC, merged