[Northants] Disable pin snapping for tree layer
mysociety/fixmystreet pull request #4004
Opened 2022-07-07 16:10 UTC by nephila-nacrea

Please check the following:

- [ ] Whether this PR should include changes to any documentation, or the FAQ;
- [ ] All cobrand-specific commits start their commit message with the cobrand in square brackets;
- [ ] Is new functionality tested? CodeCov will warn you about the diff coverage, but won’t complain about e.g. new files;
- [ ] Will cobrand-specific changes require additional work to ensure consistent behaviour on www.fixmystreet.com? 
- [ ] Are the changes tested for accessibility?
- [ ] Have you updated the changelog? If this is not necessary, put square brackets around this: skip changelog

Please check the contributing docs, and describe your pull request here.
Screenshots or GIF animations (using e.g. LICEcap) may be helpful.

Please include any issues that are fixed, using "fixes" or "closes" so that
they are auto-closed when the PR is merged.

Thanks for contributing!

2022-07-11 16:16 UTC, dracos requested changes
Good work on tracking this down - I think it could be a tiny bit clearer/similar to existing code if it acted a bit 'higher up' as explained in the line comment. Hope that makes sense :)

2022-07-11 16:16 UTC, dracos commented on web/cobrands/northamptonshire/assets.js
> +  "disable_pin_snapping": "true",
As discussed, and as per your comment above, this isn't actually to do with the existing `disable_pin_snapping` code which is for disabling a different type of pin snapping. So whilst you could have a different name - `disable_nearest_asset_snapping` perhaps - I think best solution is actually to set `snap_threshold` to 0 directly on this object, as the existing code checks that.

2022-07-11 16:16 UTC, dracos commented on web/cobrands/fixmystreet/assets.js
> +            if (this.fixmystreet.ignore_missing_asset || !this.visibility) {
I don't think we need this variable - we shouldn't be calling asset_not_found at all if we don't care about it not being found :) Proposed solution elsewhere.

2022-07-14 20:12 UTC, davea approved these changes

2022-08-10 09:58 UTC, merged