[WIP] [Oxf] Query WFS for roadworks
mysociety/fixmystreet pull request #4025
Opened 2022-07-22 18:38 UTC by nephila-nacrea

Please check the following:

- [ ] Whether this PR should include changes to any documentation, or the FAQ;
- [ ] All cobrand-specific commits start their commit message with the cobrand in square brackets;
- [ ] Is new functionality tested? CodeCov will warn you about the diff coverage, but won’t complain about e.g. new files;
- [ ] Will cobrand-specific changes require additional work to ensure consistent behaviour on www.fixmystreet.com? 
- [ ] Are the changes tested for accessibility?
- [ ] Have you updated the changelog? If this is not necessary, put square brackets around this: skip changelog

Please check the contributing docs, and describe your pull request here.
Screenshots or GIF animations (using e.g. LICEcap) may be helpful.

Please include any issues that are fixed, using "fixes" or "closes" so that
they are auto-closed when the PR is merged.

Thanks for contributing!

2022-11-09 22:26 UTC, davea commented
I'm seeing an intermittent error in the Cypress test:
```
  1) Oxfordshire highways messages displays nearby roadworks when no highways messages:
     CypressError: Timed out retrying: cy.click() failed because this element is detached from the DOM.

<label class="govuk-label govuk-radios__label" for="category_5">Flytipping</label>

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > cy.contains()

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom
      at Object.cypressErr (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:86207:11)
      at Object.throwErr (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:86162:18)
      at Object.throwErrByPath (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:86194:17)
      at Object.retry (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:76849:16)
      at retryActionability (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:65238:19)
      at tryCatcher (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:120203:23)
      at Function.Promise.attempt.Promise.try (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:117478:29)
      at tryFn (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:77307:21)
      at whenStable (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:77342:12)
      at http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:76892:16
      at tryCatcher (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:120203:23)
      at Promise._settlePromiseFromHandler (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:118139:31)
      at Promise._settlePromise (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:118196:18)
      at Promise._settlePromise0 (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:118241:10)
      at Promise._settlePromises (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:118320:18)
      at Promise._fulfill (http://oxfordshire.localhost:3001/__cypress/runner/cypress_runner.js:118265:18)
```

2022-11-18 14:43 UTC, davea requested changes
There's a flapping test when I'm running this locally.

2022-11-21 17:13 UTC, MorayMySoc commented
I'm not getting the error, but hopefully a few waits might "delay Cypress from running new commands". Let me know if that works for you and seems like a viable solution.

2022-11-29 10:42 UTC, davea approved these changes
Test is still misbehaving locally, but if it's OK for you and GH actions then so be it! 👍

2023-01-27 16:38 UTC, dracos commented
I've rebased this, removed the fixture() lines (they weren't doing anything), and removed the wait(1000)s and replaced them with waits for report-ajax which matches other tests and should resolve any flapping caused by that fetch on page load. And added a couple of scrolls into view to fix issues where the roadworks were further down than the tests expected.

2025-09-03 12:29 UTC, dracos commented
This didn't go ahead

2025-09-03 12:29 UTC, closed without merging