[Thamesmead] Stats on landing page to reflect Thamesmead only reports
mysociety/fixmystreet pull request #4030
Opened 2022-07-28 08:21 UTC by MorayMySoc

* Landing page shows Thamesmead stats and not FMS stats
* /reports goes to Thamesmead reports, not FMS reports
* Removes Thamesmead from best performing council table as not a council
* Removes Thamesmead categories from top five stats

[skip changelog]

2022-07-28 09:52 UTC, davea commented on perllib/FixMyStreet/Script/UpdateAllReports.pm
> +        cobrand => { '!=', 'thamesmead' },
This would still include Thamesmead reports made on FMS.com, I think.

2022-07-28 09:53 UTC, davea commented on perllib/FixMyStreet/Script/UpdateAllReports.pm
> +        next if $body->name eq 'Thamesmead';
Would be better to exclude this from the `search` above, I guess, rather than skipping here.

2022-07-28 16:32 UTC, chrismytton reviewed
Moray and I spoke on Slack about this, decided to split the changes in the cobrand file into a separate PR: https://github.com/mysociety/fixmystreet/pull/4033

Going to leave the other changes for @davea to re-review.

2022-08-01 13:57 UTC, davea requested changes
I think there's a bit of tidying up to be done after #4033 was merged, and a test of the new behaviour would be good too.

2022-08-26 17:20 UTC, MorayMySoc commented
I added to the test, which fails when if this worked, I don't think it should. I've pushed it up with the error to demonstrate. Was trying to debug, but the file to messy to add to this and have run out of time, for the time being...

2022-09-01 10:10 UTC, merged