[National Highways] Forward council litter responsibilities to FMS
mysociety/fixmystreet pull request #4114
Opened 2022-09-21 09:26 UTC by MorayMySoc

* Adds a parameter 'he_referral' when directing to cooridinates on FMS
* When 'he_referral' is present:
	- filters highways category to only contain council litter categories
	- triggers automatic selection of highways category
	- adds message to say to choose one of the councils litter categories
	- adds cypress test

[skip changelog]

2022-09-21 09:29 UTC, MorayMySoc commented
@davea More cypress test fun! I've tried to mock a National Highways road in the cypress test - and taken the road into Qgis to get co-ordinates on that road. So according to me, that should trigger the Highways experience of getting a 'is this on the $road' message. But it's not. Would you mind having a look to see if what I'm doing wrong is obvious?

2022-09-26 11:05 UTC, davea reviewed
The page is skipping the category selection and going straight to the "Public details" section which usually means there aren't any categories to choose from. Are you sure the fixture sets things up correctly? Can you reproduce the correct behaviour if your DB contains the same bodies/categories as the fixture?

![image](https://user-images.githubusercontent.com/4776/192260779-edf87b4f-f133-4bb4-9a04-45723536c7f8.png)

2022-09-26 11:13 UTC, MorayMySoc commented on templates/web/highwaysengland/report/new/roads_message.html
> +        <a class="js-update-coordinates" href="http://www.fixmystreet.com/report/new?latitude=[% latitude %]&amp;longitude=[% longitude %]&amp;he_referral=1">FixMyStreet</a> to continue reporting you
Good catch - I'd switched to localhost for testing and missed the http on switching back

2022-09-27 14:38 UTC, MorayMySoc commented
@davea Did you change anything else, other than the name of the test? I seem to be having a different outcome to you, which seems odd as the test should run the same for both of us...or maybe I'm catching it at a different point?

![image](https://user-images.githubusercontent.com/87022664/192556471-bd4f4de8-6378-4a27-9760-0ed147b89c5b.png)

2022-10-07 16:23 UTC, MorayMySoc commented
Sorry - put it on staging intended for client review and realised the link wouldn't work...

2022-10-10 13:10 UTC, davea submitted a review, later dismissed

2022-10-10 13:13 UTC, davea requested changes
Just one tiny thing.

(Sorry, clicked approve initially and then I spotted the `</p>` thing)

2022-10-10 13:13 UTC, davea commented on templates/web/highwaysengland/report/new/roads_message.html
> +</p>
Think this line needs to be below the `[% END %]`

2022-10-10 13:37 UTC, davea approved these changes

2022-10-13 08:50 UTC, dracos commented
As this is an improvement to the journey for .com, do we need to get client approval? I guess nice to ask for feedback but I wouldn't want them to dictate timescales or anything if we're happy it makes a better journey in general, we should get it out there.

2022-10-14 09:20 UTC, merged