[Brent] Look for Azure name in correct parameters
mysociety/fixmystreet pull request #4224
Opened 2022-12-13 17:42 UTC by MorayMySoc

Azure oidc payload is client specific for details like name and email.

Change to make parameter fetching cobrand specific
and adapts Westminster and Hackney to use this.

[skip changelog]

2022-12-14 18:11 UTC, dracos requested changes
Few tiny things is all!

2022-12-15 09:38 UTC, MorayMySoc commented on t/Mock/Facebook.pm
> +has cobrand => (
Apparently not...though it did seem to error for me requiring that fix at one point. Not sure why it doesn't need that, but the test is running fine without.

2022-12-15 10:39 UTC, dracos approved these changes

2022-12-15 15:16 UTC, merged

2022-12-15 16:43 UTC, MorayMySoc commented
@dracos Should I factor out the core side of this and do a PR against master to avoid any need to remember to deal with it for Camden?

2022-12-15 16:48 UTC, dracos commented
Sounds good, yep!