[Camden] Add Housing Estate custom JS and templates
mysociety/fixmystreet pull request #4226
Opened 2022-12-14 19:05 UTC by chrismytton

This prevents reports from being made on housing estate land and shows a not maintained message.

The asset config changes in `/data/servers` are in commit `7b54f1179fe6d9c43b17c3ad0f429f04090b9abf` on the `camden-housing-estates-asset-layer` branch.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/22996/207689803-988466de-ef47-4d33-a0da-30a946d69197.png">

Fixes https://github.com/mysociety/societyworks/issues/3416

2022-12-15 09:22 UTC, chrismytton commented
Tests are also failing on master. Seems that the /around page is taking ~10s to respond, but when I turn my wifi off the /around page loads near-instantly. So I think there's an external dependency in the Cypress tests which is currently going slower than it should be, which is causing these two Cypress tests to fail.

2022-12-15 16:04 UTC, chrismytton commented
@dracos Tests are passing now so this is ready for review.

2022-12-15 17:03 UTC, dracos requested changes
The code in mysociety-servers doesn't work as is, I think - the propertyName of the default and the housing layer combine to produce Obj/pgid/Obj which doesn't work. Think propertyName shouldn't be in default but on the layers themselves if they're different.

Couple of other queries to consider :)

2022-12-15 17:17 UTC, chrismytton commented
> The code in mysociety-servers doesn't work as is, I think - the propertyName of the default and the housing layer combine to produce Obj/pgid/Obj which doesn't work. Think propertyName shouldn't be in default but on the layers themselves if they're different.

Thanks, I didn't have the `- symlink` line in my local config, which was enough of a difference from the staging config that it was working locally but not remotely 🤦

2022-12-15 17:17 UTC, chrismytton commented
Have moved the `propertyNames` onto the individual layers in `97777805d728dbeb1ea79d8f3d3f11f4adbcc2d5` on `/data/servers`.

2022-12-15 17:20 UTC, chrismytton commented on templates/web/fixmystreet.com/report/new/roads_message.html
> +    <div id="js-housing-estate-restriction" class="js-responsibility-message hidden">
Good idea. Have done that in `44ef48d7232d6fb7ade680b0b7f29a3f0c79f63d` and made the /data/servers change in `d533b0e625e525fb342875f614e277d5298fb297`.

2022-12-16 15:16 UTC, chrismytton commented on web/cobrands/fixmystreet-uk-councils/assets.js
> +        // Need to pass a criterion function to force the not found message to be shown.
Yeah I think just doing it for Camden categories makes sense.

Have added a change in e8eec30dd0fe5805640888dadacc9efbb5b233de to only disable for the exclusively Camden categories.

2023-01-10 10:56 UTC, dracos approved these changes
Looks good - it'd be great to have a Cypress test of this behaviour at some point.

2023-01-11 11:07 UTC, merged