[Buckinghamshire] Move assets to configuration.
mysociety/fixmystreet pull request #4265
Opened 2023-01-19 09:24 UTC by dracos

[skip changelog]

<details>
<summary>New asset configuration</summary>
<pre>
buckinghamshire:
  - - name: 'default'
      http_wfs_url: "https://tilma.staging.mysociety.org/mapserver/bucks"
      asset_type: 'spot'
      max_resolution: 4.777314267158508
      asset_id_field: 'central_as'
      attributes:
        central_asset_id: 'central_as'
        site_code: 'site_code'
      geometryName: 'msGeometry'
      srsName: "EPSG:27700"
      body: "Buckinghamshire Council"
    - name: 'labeled'
      http_wfs_url: "https://tilma.staging.mysociety.org/mapserver/bucks"
      asset_type: 'spot'
      max_resolution: 4.777314267158508
      asset_id_field: 'central_as'
      attributes:
        central_asset_id: 'central_as'
        site_code: 'site_code'
      geometryName: 'msGeometry'
      srsName: "EPSG:27700"
      body: "Buckinghamshire Council"
      select_action: true
      feature_code: 'feature_id'
      stylemap: fixmystreet.assets.buckinghamshire.streetlight_stylemap
      construct_asset_name: fixmystreet.assets.buckinghamshire.labeled_construct_asset_name
      actions:
        asset_found: fixmystreet.assets.named_select_action_found
        asset_not_found: fixmystreet.assets.named_select_action_not_found
  - wfs_feature: "Grit_Bins"
    asset_category:
      - "Salt bin damaged"
      - "Salt bin refill"
    asset_item: 'grit bin'
  - template: 'labeled'
    wfs_feature: "StreetLights_Union"
    class: OpenLayers.Layer.VectorAssetMove
    asset_category:
      - 'Light on during the day'
      - 'Street light dim'
      - 'Street light intermittent'
      - 'Street light not working'
    asset_item: 'street light'
    asset_item_message: 'You can pick a <b class="asset-ITEM">ITEM</b> from the map &raquo;<br>If there is no yellow dot showing then this ITEM is not maintained by Transport for Buckinghamshire'
    construct_selected_asset_message: fixmystreet.assets.buckinghamshire.streetlight_construct_selected_asset_message
    actions:
      asset_found: fixmystreet.assets.buckinghamshire.streetlight_asset_found
      asset_not_found: fixmystreet.assets.buckinghamshire.streetlight_asset_not_found
  - template: 'labeled'
    wfs_feature: "IlluminatedBollards"
    asset_category:
      - "Bollard light not working"
    asset_item: 'bollard'
  - template: 'labeled'
    wfs_feature: "Bollards"
    asset_category:
      - "Bollards or railings"
    asset_item: 'bollard'
  - template: 'labeled'
    wfs_feature: "Beacons"
    asset_category:
      - 'Belisha Beacon broken'
    asset_item: 'belisha beacon'
  - template: 'labeled'
    wfs_feature: "Beacon_Column"
    asset_category:
      - 'Belisha Beacon broken'
    asset_item: 'belisha beacon'
  - template: 'labeled'
    wfs_feature: "Crossings"
    asset_category:
      - 'Traffic lights & crossings problems with buttons, beep or lamps'
      - 'Traffic lights & crossings problems with timings'
    asset_item: 'crossing'
  - template: 'labeled'
    wfs_feature: "Signs_Union"
    asset_category:
      - 'Sign light not working'
    asset_item: 'sign'
    # Want to show signs for the parish "Dirty signs" categories, so skip body checks.
    body: ~
  - template: 'labeled'
    wfs_feature: "BusStops"
    asset_group: "Bus stop/shelter issue"
    construct_asset_name: ~
    asset_item: 'bus stop'
    asset_id_field: 'feature_id'
    attributes:
      bus_stop_number: 'feature_id'
  - http_wfs_url: "https://[% tilma_host %]proxy/bcc/drains/wfs"
    wfs_feature: "junction_inspections"
    propertyNames:
      - 'id'
      - 'msGeometry'
      - 'asset_id'
      - 'created'
      - 'junction_cleaned'
    stylemap: fixmystreet.assets.stylemap_invisible
    asset_category:
      - "Blocked drain"
    asset_item: 'drain'
    non_interactive: true
    name: "Bucks Junction Inspections"
  - http_wfs_url: "https://[% tilma_host %]/proxy/bcc/drains/wfs"
    wfs_feature: "junctions"
    propertyNames:
      - 'id'
      - 'msGeometry'
      - 'asset_id'
      - 'created'
      - 'last_inspected'
    asset_category:
      - "Blocked drain"
    asset_item: 'drain'
    select_action: true
    construct_selected_asset_message: fixmystreet.assets.buckinghamshire.drains_construct_selected_asset_message
    actions:
      asset_found: fixmystreet.assets.named_select_action_found
      asset_not_found: fixmystreet.assets.named_select_action_not_found
  - wfs_feature: "Whole_Street"
    propertyNames:
      - 'msGeometry'
      - 'site_code'
      - 'feature_ty'
    stylemap: fixmystreet.assets.buckinghamshire.street_stylemap
    non_interactive: true
    road: true
    asset_item: 'road'
    asset_type: 'road'
    asset_group:
      - 'Drainage issues'
      - 'Flytipping'
      - 'Roads & Pavements'
      - 'Salt & Gritting'
      - 'Street Lights'
      - 'Street Signs'
      - 'Traffic Lights and crossings'
      - 'Trees and vegetation'
      - 'Trees'
      - 'Grass, hedges and weeds'
    actions:
      found: fixmystreet.assets.buckinghamshire.street_found
      not_found: fixmystreet.assets.buckinghamshire.street_not_found
    no_asset_msg_id: '#js-not-a-road'
    no_asset_msgs_class: '.js-roads-bucks'
    usrn:
      attribute: 'site_code'
      field: 'site_code'
    filter_key: 'feature_ty'
    filter_value: fixmystreet.assets.buckinghamshire.types_to_show
  - wfs_feature: "WinterRoutes"
    asset_category: "Snow and ice problem/winter salting"
    asset_item: "road"
    asset_type: "road"
    non_interactive: true
    road: true
    actions:
      found: fixmystreet.assets.buckinghamshire.winter_found
      not_found: fixmystreet.assets.buckinghamshire.winter_not_found
  - http_wfs_url: 'https://maps.buckscc.gov.uk/arcgis/services/Transport/BC_Car_Parks/MapServer/WFSServer'
    wfs_feature: "BC_CAR_PARKS"
    class: OpenLayers.Layer.VectorAssetMove
    select_action: true
    actions:
      asset_found: fixmystreet.message_controller.asset_found
      asset_not_found: fixmystreet.message_controller.asset_not_found
    asset_group: "Car park issue"
    asset_item: "car park"
    asset_type: "area"
    asset_item_message: "Pick a <b class=\"asset-ITEM\">ITEM</b> on the map &raquo;<br>Only car parks marked on the map with a grey box are maintained by Buckinghamshire"
    no_asset_msg_id: '#js-not-council-car-park'
    stylemap: fixmystreet.assets.buckinghamshire.car_parks_stylemap
    protocol_class: OpenLayers.Protocol.BuckinghamshireHTTP
  - http_wfs_url: 'https://maps.buckscc.gov.uk/arcgis/services/Transport/OS_Highways_Speed/MapServer/WFSServer'
    wfs_feature: "OS_Highways_Speed:CORPGIS.CORPORATE.OS_Highways_Speed"
    propertyNames:
      - 'speed'
      - 'shape'
    actions:
      found: fixmystreet.assets.buckinghamshire.speed_found
      not_found: fixmystreet.assets.buckinghamshire.speed_not_found
    no_asset_msg_id: '#js-not-a-road'
    asset_category:
      - "Grass cutting"
      - "Hedge problem"
      - "Dirty signs"
    non_interactive: true
    road: true
    asset_item: 'road'
    asset_type: 'road'
    stylemap: fixmystreet.assets.stylemap_invisible
    # Want to use this for parish categories as well as Bucks, so skip body checks.
    body: ~
</pre>
</details>

2023-01-23 13:07 UTC, davea requested changes
Looks good, but a couple of small issues with the `asset_item_message` values in the suggested config:

The `»` character isn't encoded correctly:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/4776/214047042-c154b2f1-1216-4d45-befd-a3037ce33447.png">

Also the suggested YAML doesn't parse due to the linebreaks in the two `asset_item_message` values. I tried putting `\n` literals in, which just show up as `\n` in the message:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/4776/214047096-01e458da-3c91-47b3-9406-937f1b49f95a.png">

Using a multiline value parses OK but the linebreaks seem to be ignored/stripped:

```yaml
        asset_item_message: |
          You can pick a ITEM from the map »
          If there is no yellow dot showing then this ITEM is not maintained by Transport for Buckinghamshire
```
<img width="438" alt="image" src="https://user-images.githubusercontent.com/4776/214047207-a05e4299-fca3-4645-908b-03e5bf15743f.png">

2023-01-23 13:59 UTC, dracos commented on data/test-asset-layers.yml
> +    attributes: ~
It seems that null in our parser is becoming the string 'null', yes.

2023-01-23 14:22 UTC, dracos commented
"The » character isn't encoded correctly:" - same issue I just fixed on Pboro bulky goods, perhaps, will look.

"Also the suggested YAML doesn't parse due to the linebreaks in the two asset_item_message values." - this is the GitHub markdown text changing the br that is there into an actual line break, sorry, didn't realise it had done that. It is `<br>` in the actual config :)

2023-01-23 14:48 UTC, davea commented
> this is the GitHub markdown text changing the br

🤦

2023-01-23 15:19 UTC, dracos commented
Encoding was the same issue, have included fix for that, and also as I'd halfway done it last week, have also added Peterborough as another move.

2023-01-23 19:00 UTC, davea approved these changes
:shipit:

2023-03-01 12:37 UTC, davea approved these changes
💡

2023-03-01 21:56 UTC, merged