[Brent] Adds request new container feature
mysociety/fixmystreet pull request #4267
Opened 2023-01-20 10:26 UTC by MorayMySoc

Adds Brent container request form as copy of Bromley and cobrand methods required for new containers.

https://github.com/mysociety/societyworks/issues/3405

[skip changelog]

2023-01-20 12:23 UTC, dracos requested changes
The table for requesting was at https://3.basecamp.com/4020879/buckets/28996137/messages/5567592629#__recording_5593027279
I'm not sure this is quite right, and is a bit confusing - your cobrand code checks `container-choice` (presumably from Kingston) but the new form (copy of Bromley) doesn't have such a field, for example. That was because Kingston is only one container at a time - which sounds like it needs to be the case here too. I'd probably start from Kingston as a base rather than Bromley, then the first page next will depend upon what container was picked. I guess communal can just not appear in the list at all, for starters, and let through the normal ones.

2023-01-23 13:03 UTC, dracos requested changes
This is lacking tests, which we need to show that the flow is working as expected. The code isn't yet self-consistent - as I raised last review, the code is checking `container-choice` in places, but you haven't got any form that contains that as an option to be filled in anywhere - the `waste_munge_request_form_fields` from CobrandSLWP.pm is missing to supply that field in a form, I think that's the main thing - sorry if I wasn't clear last time on that. There are still a number of Bromley or Kingston specific things that are potentially going to confuse things if we somehow think they're now needed here.
Please add the container-choice form, remove other-cobrand specific things so there is a basic request flow without special cases (or at least, include Brent ones :) ), and add some tests that the flow works and we get a correct-looking report at the end of it (you can almost certainly base tests upon existing Kingston/Sutton request tests).

2023-01-23 17:09 UTC, MorayMySoc commented on perllib/FixMyStreet/Cobrand/Brent.pm
> +    if ($id == 44) {
@dracos Where/how are these 'set_param's being used? Is it just in templates? I'm not seeing where they get picked up otherwise.

2023-01-23 17:14 UTC, dracos commented on perllib/FixMyStreet/Cobrand/Brent.pm
> +    if ($id == 44) {
So `set_param` sets the query parameter as if the form field was being submitted as an extra question in the new report form, which means the new report code fetches it from there and adds it to the relevant extra data field.

2023-01-25 14:24 UTC, dracos approved these changes
Looks good, thanks for the tests :)
I've added a commit with some small changes I found whilst reviewing, was easier than giving them all as PR feedback - hopefully switched to what may be correct IDs (we'll see), hid those two options from garden bin as well as refuse bin (after adding garden bin to list of containers), fixed the event ID, put the notes_damaged in (might as well as you're asking for it), added the closed_event to match SLWP. Please do check that over for me :)

2023-01-25 15:09 UTC, dracos commented
Just noticed, tests are slow because it's requesting BH JSON a lot.

2023-01-26 17:51 UTC, merged