[FMS] Added 20th anniversary badge in the frontpage header
mysociety/fixmystreet pull request #4274
Opened 2023-01-31 10:12 UTC by lucascumsille

Fixes part of: https://github.com/mysociety/Design-Internal-tasks/issues/8

<img width="368" alt="Screenshot 2023-01-31 at 10 10 50" src="https://user-images.githubusercontent.com/13790153/215731508-60aa7e6e-7da2-47aa-9dd2-aceade4652ea.png">
<img width="1112" alt="Screenshot 2023-01-31 at 10 01 47" src="https://user-images.githubusercontent.com/13790153/215731519-da2e9c3f-c7fe-4f49-96bb-631418b382e3.png">

2023-01-31 16:18 UTC, zarino requested changes
Given we’re about to do a bunch of these, it feels like we should try and get some simple concepts down that we can apply the same everywhere.

I’ve left some comments inline, about sizing and CSS selectors.

I also feel like we could make our lives much easier if we removed the empty space from the top of the graphic itself (so the top of the "banner" touches the top of the SVG/PNG). Then there’d be less need for negative margins / positioning, maybe?

2023-01-31 16:18 UTC, zarino commented on web/cobrands/fixmystreet.com/layout.scss
> +            width: $mysociety-badge-width;
You set a `width` for the SVG, but not a `height`, meaning that keeps the original 266px height from the inline `height="266"` attribute. As a result, the hitbox for the SVG’s wrapper link is much taller than the SVG itself, which is a bit weird:

<img width="231" alt="Screenshot 2023-01-31 at 15 59 30" src="https://user-images.githubusercontent.com/739624/215814628-93809cc5-debe-4d98-bbf6-356d40d6fba6.png">

I’d set `height: auto` on the SVG. In fact, I’d probably leave all the sizing to `#mysociety-badge` instead, with something like this:

```scss
#mysociety-badge {
  width: $mysociety-badge-width;

  svg {
    width: 100%;
    height: auto;
  }
}
```

2023-01-31 16:18 UTC, zarino commented on web/cobrands/fixmystreet.com/base.scss
> +  $mysociety-badge-width: 90px;
Maybe it’s just me, but I find this a smidge too large, it feels like it’s overpowering the FMS logo beside it:

![Screen Shot 2023-01-31 at 16 09 10](https://user-images.githubusercontent.com/739624/215815871-83c9bb96-5bee-4fdf-87c4-b842f30ef52f.png)

Here’s how it looks reduced from 90px to 75px – a bit more balanced?

![Screen Shot 2023-01-31 at 16 09 04](https://user-images.githubusercontent.com/739624/215815949-bb1e6d51-ecb4-45bb-a37c-1de9808c0b2d.png)

2023-01-31 16:18 UTC, zarino commented on web/cobrands/fixmystreet.com/layout.scss
> +    $fms-logo-width: 200px;
Again, this feels very large to me, especially given we’ve reduced the size of the FMS logo at the same time.

2023-01-31 16:18 UTC, zarino commented on web/cobrands/fixmystreet.com/layout.scss
> +        top: calc((#{$fms-logo-height} + #{$fms-logo-vertical-margin}) * -1);
This all seems massively overcomplicated – do we _have_ to do all of this calculation? And why do we need to set a `max-height`?

2023-02-01 09:16 UTC, lucascumsille commented
Thanks for the feedback @zarino 

- To get rid of the extra space on the top I vertically lowered the dropshadow on the badge so it doesn't use space on the top.
- I reduced the size in both, mobile and desktop.
- Some improvements to make to code less complicated.

Let me know what you think

<img width="997" alt="Screenshot 2023-02-01 at 09 13 54" src="https://user-images.githubusercontent.com/13790153/216000853-9d4929f3-bcb7-4f82-9d88-9d24e015111f.png">
<img width="370" alt="Screenshot 2023-02-01 at 09 14 10" src="https://user-images.githubusercontent.com/13790153/216000863-70768da4-228b-46b8-a768-c4042a405948.png">

2023-02-06 12:45 UTC, zarino reviewed
Maybe it’s just me, but I feel like something about the spacing of this corner feels weird:

<img width="473" alt="Screenshot 2023-02-06 at 12 40 22" src="https://user-images.githubusercontent.com/739624/216974017-c689871a-ae23-4ffa-9bdd-8fafeb71d27b.png">

Maybe it’s the massive vertical padding (well, `margin`) above/below the FMS logo compared with the narrow vertical padding inside the yellow hero section.

Maybe it’s the difference in size between the FMS logo (quite small – or rather, much smaller than it currently is on the live site) and the banner (quite large).

I get that you’ve tried to keep the FMS logo small, so that the nav menu to the right has the same amount of space as it currently has on the banner-less live site. But that does mean the FMS logo looks quite pokey next to this massive banner.

Hmmm… not sure. But something here just doesn’t feel right.

2023-02-07 08:54 UTC, lucascumsille commented
> Maybe it’s just me, but I feel like something about the spacing of this corner feels weird:
> 
> <img alt="Screenshot 2023-02-06 at 12 40 22" width="473" src="https://user-images.githubusercontent.com/739624/216974017-c689871a-ae23-4ffa-9bdd-8fafeb71d27b.png">
> 
> Maybe it’s the massive vertical padding (well, `margin`) above/below the FMS logo compared with the narrow vertical padding inside the yellow hero section.
> 
> Maybe it’s the difference in size between the FMS logo (quite small – or rather, much smaller than it currently is on the live site) and the banner (quite large).
> 
> I get that you’ve tried to keep the FMS logo small, so that the nav menu to the right has the same amount of space as it currently has on the banner-less live site. But that does mean the FMS logo looks quite pokey next to this massive banner.
> 
> Hmmm… not sure. But something here just doesn’t feel right.

I get what you say, in this case I think I will increase the size of the FMS logo, because in the current mockup you can barely notice "mySociety" in the badge.

2023-02-07 09:07 UTC, zarino commented
Yeah, I’d deffo make the FMS logo _bigger_ rather than the badge _smaller_.

2023-02-10 15:41 UTC, zarino approved these changes
@lucascumsille sorry for the delay in revisiting this. I’ve pushed a number of commits which—if you’re happy with them—you’ll probably just want to squash into a single commit for all of these changes. I’ve:

- Removed the `badge-mysociety-*.png` image files and the `.mysociety-badge__fallback` element and styling, as it doesn’t seem we were actually _attempting_ to display the badge on non-homepage headers (at least, it wasn’t visible).
- Swapped the `badge_mysociety_*.svg` files with versions that have 1) 10px less empty space at the bottom, and 2) a more subtle shadow.
- Slightly bumped up the size of the FMS logo even further.
- Given the nav bar a margin-left, so that the nav items wrap onto two lines when there isn’t space (window widths around 750–850px), rather than overlapping on top of the FMS logo.
- Removed the animation and hover `scale()` effect on the badge and FMS logo (do we really _need_ hover effects on these?) but replicated the yellow focus `outline` on the nav items too, for consistency.

2023-03-06 08:48 UTC, merged