Offline reporting functionality
mysociety/fixmystreet pull request #4290
Opened 2023-02-10 15:00 UTC by davea

- Adds report form to offline fallback page
 - Automatically saves data from that form as a draft report in IndexedDB
 - Button on front page to continue draft report on normal /report/new flow when back online
 - Edits made to report when continuing draft are saved
 - Uses Dropzone for photo handling, stores images in IndexedDB

Bugs yet to be fixed:
 - [x] Correctly submitting photos to server when continuing draft
 - [x] Clearing draft when back online and report successfully submitted
 - [ ] Front page 'continue draft' button missing from some cobrands
 - [ ] Needs front end tests

Outstanding features required for parity with existing app:
 - [ ] Multiple drafts

Future improvements:
 - Automatically start draft when going through /report/new flow in usual online manner
 - ???

For https://github.com/mysociety/fixmystreet/issues/2221

# Screenshots

**NB** This would all probably benefit from some design love :)

The offline page now has a form for storing a draft report:

<img width="50%" src="https://user-images.githubusercontent.com/4776/219393617-03121561-8024-4599-b07d-497ba5a6c68a.png" />

Users can store their current location, attach photos with the usual Dropzone UI, and enter a title & description of the problem:

<img width="50%" src="https://user-images.githubusercontent.com/4776/219393802-88c93a8f-83da-40c7-9e11-e21113732b77.png" />

Their changes are automatically persisted with every keypress. There's a timestamp of when the report was saved. There's also a timestamp in the footer that shows when the offline page was cached, for debugging purposes:

<img width="50%" src="https://user-images.githubusercontent.com/4776/219393919-e6c1baa3-8f60-4709-b019-7be95e611024.png" />

When the user goes back online, the front page has a big button to continue & submit their draft report:

<img width="50%" src="https://user-images.githubusercontent.com/4776/219394407-2228c22d-66ba-42f0-b079-bc6685d10bac.png" />

This takes the user through the usual reporting flow, but their draft report's location/photos/text are all automatically populated in the report form:

<img width="50%" src="https://user-images.githubusercontent.com/4776/219394827-25167fea-3ab9-47cb-b1ae-2fffe4d6328f.png" />

<img width="50%" src="https://user-images.githubusercontent.com/4776/219395954-a700fc49-e339-4da5-8470-24b7365b22a8.png" />

<img width="50%" src="https://user-images.githubusercontent.com/4776/219395975-80a88403-7b3e-41cf-a5b0-39e56c1bafda.png" />

2023-03-07 14:40 UTC, davea commented
It's not perfect yet @dracos but it's in good enough shape I think to review.

2023-03-24 14:10 UTC, dracos requested changes
Works well :)
I think small issues I have (e.g. how to remove a draft if you don't finally submit it and aren't offline again) will be resolved by allowing multiple drafts anyway - we will have a client-side "Your drafts" page/view on the offline page that could let you do that if you have drafts, offline or no, for example.
I've pushed a few small improvements to the text/date/etc, let me know if you disagree ;) Main decision then is how to let people know about the draft they have. I've pushed a number of different options, but I think my favourite is the floating bottom right red box that lets them know they have one to continue. Let me know what you think. But with that decided/tidied I think this could be good to go

2023-03-24 14:10 UTC, dracos commented on templates/web/base/around/postcode_form.html
> +            <p class="hidden js-continue-draft">
I've done a number of options - red dot on the menu, made front page option more prominent, and a floating bottom right button. I think I like the last the most - obvious, but not in the way, seems to be where other sites put notification type thing. Needs a bit of work to tidy up, but then I think that could be a little separate piece of code from the rest.
<img width="510" alt="image" src="https://user-images.githubusercontent.com/154364/227542450-7b16e90d-bf88-40ba-972a-dea1a9a85f72.png">

2023-04-04 15:46 UTC, davea commented
I've moved the multiple drafts commit into [its own branch](https://github.com/mysociety/fixmystreet/tree/offline-multiple-drafts), and twiddled the front page JS to hopefully be as small a change as required as well as moving the new nav item into the template rather than building dynamically.

2023-04-05 15:50 UTC, dracos requested changes
A couple of small things (rename an ID and changing the button layout) is all, then think good to go :)

2023-04-05 16:27 UTC, dracos commented on templates/web/base/offline/fallback.html
> +    <p><button class="btn-danger btn--small js-delete-drafts" data-confirm="Are you sure?">Delete draft</button></p>
Have pushed small change for A from that web page:
![image](https://user-images.githubusercontent.com/154364/230144274-f155d4a3-318a-4637-878a-6ea1fcbc4d1b.png)

2023-04-06 12:11 UTC, merged