[Northumberland] Add contact-by-phone information to FAQ
mysociety/fixmystreet pull request #4416
Opened 2023-05-04 10:11 UTC by chrismytton

Add a section to the FAQ page about contacting the council by phone.

Fixes https://github.com/mysociety/societyworks/issues/3629

To see the actual changes you can run:

```
git diff --no-index templates/web/fixmystreet-uk-councils/about/faq-en-gb.html templates/web/northumberland/about/faq-en-gb.html
```

2023-05-04 17:33 UTC, dracos requested changes
Some typos I'm afraid

2023-05-04 17:33 UTC, dracos commented on templates/web/northumberland/about/faq-en-gb.html
> +<b>Contact us by phone</b>
This probably should be wrapped in a `<p>`

2023-05-04 17:33 UTC, dracos commented on templates/web/northumberland/about/faq-en-gb.html
> +<p>If you have speech of hearing difficulties you acn use Relay UK to contact us by dialing 018001 01670 623515. <a href="https://www.relayuk.bt.com/">Find more information about Relay UK</a>.</p>
Couple of typos here:
```suggestion
<p>If you have speech or hearing difficulties you can use Relay UK to contact us by dialling 018001 01670 623515. <a href="https://www.relayuk.bt.com/">Find more information about Relay UK</a>.</p>
```

2023-05-04 17:33 UTC, dracos commented on templates/web/northumberland/about/faq-en-gb.html
> +<b>Customers with speed or hearing difficulties</b>
And here (also within a `<p>`):
```suggestion
<b>Customers with speech or hearing difficulties</b>
```

2023-05-05 08:04 UTC, chrismytton commented
That'll teach me to copy/paste without proof reading 🙄

2023-05-05 08:10 UTC, dracos approved these changes
☎️

2023-05-05 08:11 UTC, merged