Switch to OSM for reverse geocoding
mysociety/fixmystreet pull request #4444
Opened 2023-05-17 12:45 UTC by davea

WIP, still needs a tidy up of all places mentioning resourceSets

[skip changelog]

2023-05-17 13:53 UTC, davea commented
@dracos not quite finished yet (need to ensure all cobrands' use of `resourceSets` can handle OSM results) but does this look like the right sort of thing?

2023-05-17 14:01 UTC, dracos reviewed
Yeah, looking good :)

2023-05-19 08:42 UTC, dracos requested changes
A few small issues, plus one large issue concerning tests making external calls.

Given the amount of code checking display_name/resourceSets, I'd later suggest we factor that into Problem.pm so it can return one canonical set of data for a geocode row perhaps, would simplify all the changes here, but probably not for now given the issue.

2023-05-19 08:42 UTC, dracos commented on t/cobrand/peterborough.t
> +    diag $mech->content;
diag left in

2023-05-19 08:42 UTC, dracos commented on perllib/FixMyStreet/Cobrand/Peterborough.pm
> +            ($number, $street) = $address->{addressLine} =~ /\s*(\d*)\s*(.*)/;
The setting of postcode from address->postalCode has been dropped.

2023-05-19 10:29 UTC, dracos approved these changes
Woo :)

2023-05-19 10:32 UTC, merged