Added GOVUK styling to 'Show my name publicly'
mysociety/fixmystreet pull request #4583
Opened 2023-08-24 10:56 UTC by lucascumsille

Fixes: https://github.com/mysociety/societyworks/issues/3825
Part of this milestone: https://github.com/mysociety/societyworks/milestone/99

<img width="648" alt="Screenshot 2023-08-24 at 11 52 45" src="https://github.com/mysociety/fixmystreet/assets/13790153/f2451a67-b5b8-49d6-b94e-fcae7b680d43">

<img width="648" alt="Screenshot 2023-08-24 at 11 52 24" src="https://github.com/mysociety/fixmystreet/assets/13790153/6a02ee8c-be73-432d-8c04-d8fc4cb6506b">

[Skip changelog]

2023-08-25 08:50 UTC, dracos requested changes
This one seems the smallest so thought might as well use this to get the forms.css in core properly and everywhere?

2023-08-25 08:50 UTC, dracos commented on templates/web/base/header.html
> +        <link rel="stylesheet" href="/vendor/govuk-frontend/forms.css">
Could this be in header/css.html (two templates), and then all the other includes of it in various header_extra.html etc can be removed.

2023-08-28 08:48 UTC, lucascumsille commented
@dracos Thanks for the feedback. I just pushed a commit that adds the GOVUK stylesheet to core and then I removed it from all the `header_extra`

2023-08-29 16:21 UTC, dracos commented
Thanks. After some more investigation of this, we can import this in base.scss, replacing the radios.css that is already there (which is a subset of this CSS). I've force-pushed this branch with that change, let me know that it's still okay for you.

(Both files are being generated from https://github.com/mysociety/fixmystreet.com/tree/master/css if we ever need to make changes at source.)

2023-08-30 05:44 UTC, lucascumsille commented
> Thanks. After some more investigation of this, we can import this in base.scss, replacing the radios.css that is already there (which is a subset of this CSS). I've force-pushed this branch with that change, let me know that it's still okay for you.
> 
> (Both files are being generated from https://github.com/mysociety/fixmystreet.com/tree/master/css if we ever need to make changes at source.)

Thanks =) yeah it's fine with me and I can see it working.

2023-08-30 07:32 UTC, merged