[Northumberland] Add shortlisted to stats summary
mysociety/fixmystreet pull request #4625
Opened 2023-09-22 14:46 UTC by MorayMySoc

https://mysocietysupport.freshdesk.com/a/tickets/3384

[skip changelog]

2023-09-22 15:44 UTC, dracos requested changes
Code works fine, but I think will have to be changed to better deal with large exports.

2023-09-22 15:44 UTC, dracos commented on perllib/FixMyStreet/Cobrand/Northumberland.pm
> +        if ($report->shortlisted_user) {
Any change to the CSV export needs to consider the effect on performance. In this case, you are asking for two new DB queries for every row being looked at (first the user planned reports table, then the user table, I can't see any prefetches). As with the `csv_staff_user_lookup` being used just above here, I think if this is a wanted column in the export, you will have to prefetch all the current shortlisted users into a hash, and then here you can then use that stored lookup.
(The other option would be to try and change the main DB query to include the shortlisted user in its results, but that seems more prune to issues.)

2023-10-03 13:37 UTC, chrismytton commented
The code was only picking up the first problem assigned to a user. Have pushed a fixup that gets all of them.

2023-10-03 14:28 UTC, chrismytton commented
Found the `shortlisted_user` method on `Problem`, so have used that instead.

2023-10-03 14:59 UTC, dracos commented
@chrismytton As per my first review, you can't use shortlisted_user, that's what this PR used originally.

2023-10-03 15:10 UTC, chrismytton commented
@dracos OK, will try and figure out why the other way wasn't working.

2023-10-20 13:41 UTC, merged