[SLWP] Adds cheque payment for K&S
mysociety/fixmystreet pull request #4685
Opened 2023-10-23 09:26 UTC by MorayMySoc

Adds the option to accept cheque payments and put in the cheque reference number avoiding the credit card payment flow.
    
https://github.com/mysociety/societyworks/issues/3952

[Skip changelog]

2023-10-23 09:31 UTC, MorayMySoc commented
Wanted to check this is broadly what's expected. I think there may be an issue in that, if you go to pay by CC changing mind and back button then going forward with cheque doesn't work. At least summary page doesn't show - also text will probably need to change from 'Continue to payment' to something like 'Make booking' I guess.

2023-10-24 13:51 UTC, dracos requested changes
Looks good, couple of small things

2023-10-24 13:51 UTC, dracos commented on perllib/FixMyStreet/App/Controller/Waste.pm
> +            $reference_text = 'paid by phone/cheque';
Could this be "reference $chequeReference (phone/cheque)" (looking up the ref) so that it matches up at the `open311-adapter` end.

2023-10-24 13:51 UTC, dracos commented on perllib/FixMyStreet/App/Form/Waste/Bulky/Shared.pm
> +            $page->form->{data}->{payment_method} = 'Credit card';
What does this line do? `payment_method` would be set to `credit_card` I would assume, anyway, so I'm hoping it's not needed.

2023-10-25 15:59 UTC, dracos approved these changes
Ta!

2023-10-25 16:57 UTC, merged