[FMS] Add parent categories to dashboard categories view
mysociety/fixmystreet pull request #4700
Opened 2023-11-01 15:22 UTC by MorayMySoc

Add a parent categories column to show if a category is a subcategory.

Arbitrary decision to choose the first parent category from the groups method of a contact.

https://github.com/mysociety/societyworks/issues/1458

[skip changelog]

2023-11-01 15:32 UTC, MorayMySoc commented
I'll need to fix and add tests, but I wanted to check that we were agreed is what's meant to be achieved

2023-11-07 17:54 UTC, MorayMySoc commented
Ok, ultimately copied the wards stuff once I understood what was going on - but as far as I see it needs to have the labels selectable in some way (either by click or input check) to select the whole group. Gone in a bit of a long loop on this, so that's actually probably what the real work of this ticket was!

2023-12-04 18:35 UTC, MorayMySoc commented
Changes the dropdown for categories in the dashboard stats to be multi-select checkboxes instead of only allowing selecting one category.

Adds group labels to group categories in the 'categories' dropdown menu of the dashboard with an all-*group-name* checkbox to select all of subcategories for that group.

https://github.com/mysociety/societyworks/issues/1458

2023-12-05 09:19 UTC, dracos requested changes
Looking better, one issue with the template change, and hopeful couple of simplifications :)

2023-12-05 09:19 UTC, dracos commented on templates/web/base/report/new/_category_select.html
> +        <option value="group-[% group.name %]" [% ' selected' IF display_categories.$pseudo_category %]>All [% group.name %]</option>
This template is included by the admin report edit category dropdown, and the old-app category select, but you only want this change to apply to the dashboard usage - pass in an `include_group_option` in the `INCLUDE` and use that?

2023-12-05 09:19 UTC, dracos commented on perllib/FixMyStreet/Reporting.pm
> +has category => ( is => 'ro', isa => Maybe[ArrayRef[Maybe[Str]]], default => sub { [] } );
Feels like we could get rid of these Maybes, the code changes in this file could be easier, e.g. if we coerced the category to always be an ArrayRef[Str], then you wouldn't need to check $self->category is set anywhere, it always would be an arrayref.

2023-12-05 09:19 UTC, dracos commented on perllib/FixMyStreet/App/Controller/Dashboard.pm
> +        if (grep { $_ =~ /^group-/ } @{ $c->stash->{category} }) {
Unless I've missed an oddity in what this is trying to do, would something like this construction have the same effect as what you're after?

```
my %group_names = map { $_->{name} => $_->{categories} } @{$c->stash->{category_groups}};
foreach (@{$c->stash->{category}}) {
    next unless /^group-(.*)/;
    for my $contact (@{$group_names{$1}}) {
        push @{ $c->stash->{category} }, $contact->category;
        push @remove_from_display, $contact->category;
    }
}
```

2023-12-05 17:19 UTC, dracos requested changes
Looking good, just one thing more for me checking I've understood it right :)

2023-12-05 17:19 UTC, dracos commented on perllib/FixMyStreet/Script/CSVExport.pm
> +        category => [],
I don't think this is needed, because of your `default`?

2023-12-06 09:27 UTC, dracos approved these changes
Thanks! All seems to work as expected :) I actually just spotted in TfL you also don't need to check the first bit of that condition now as you know it will be an arrayref, but it's fine as is as well.

2023-12-06 09:38 UTC, MorayMySoc commented
Sorry to force a re-review but figured I may as well get that done too - but wanted to check I haven't misunderstood and got it wrong either.

2023-12-06 09:40 UTC, dracos approved these changes
No worries, yes, that's what I meant - think `->category` is guaranteed to be an arrayref now, which makes things bit neater :)

2023-12-06 10:34 UTC, merged