[Brent] Allow reporting of missed small items if overdue
mysociety/fixmystreet pull request #4736
Opened 2023-11-22 18:06 UTC by MorayMySoc

Allow open small items events through and check if they are overdue. If they are allow them to be reported as missed.

https://mysocietysupport.freshdesk.com/a/tickets/3500

[skip changelog]

2023-11-24 12:52 UTC, dracos requested changes
Couple of issues, I think, but general looks okay.
I think however (after this PR) it will need adapting to cope with more than one bulky event being found...

2023-11-27 13:05 UTC, MorayMySoc commented on perllib/FixMyStreet/Cobrand/Brent.pm
> +    my $duration = $today-$collection_due_date;
It looks like if the date and time is the same it will return false so have set the times to be the same

2023-11-27 14:06 UTC, dracos commented on perllib/FixMyStreet/Cobrand/Brent.pm
> +    my $duration = $today-$collection_due_date;
truncate( to => 'day') is the usual way of doing this.

2023-11-29 09:39 UTC, dracos requested changes
One query to ask Brent about, I guess.
Not necessarily wanting to expand this, but from K&S work I see that this code won't work if someone has more than one bulky collection active - we're only ever storing one such here. Do you think it would be much work to have it store multiple if it finds them, and use them?

2023-11-29 09:39 UTC, dracos commented on perllib/FixMyStreet/Roles/CobrandEcho.pm
> +                    date => construct_bin_date({ DateTime => $report->get_extra_field_value('Collection_Date')}),
We may fetch an event with this API call that doesn't exist in our system (if it was created outside our system), so I guess in that case we shouldn't set this object at all, as we won't know the collection date then. (Also, we could ask Brent if there is a field on a bulky collection event that is the collection date, and then use that (perhaps I should have suggested asking that in my last comment).)

2024-11-05 17:42 UTC, dracos commented
I think this was done as https://github.com/mysociety/fixmystreet/pull/5073

2024-11-05 17:42 UTC, closed without merging