[West Northants] Initial setup.
mysociety/fixmystreet pull request #4744
Opened 2023-11-29 13:30 UTC by neprune

[skip changelog]

2023-12-04 11:23 UTC, dracos requested changes
A few things that probably date from how old the original cobrand is, and a couple of other minor things, looking good :)

2023-12-05 11:25 UTC, neprune commented on perllib/FixMyStreet/Cobrand/WestNorthants.pm
> +}
I thought this wouldn't be needed because the older reports would still be under the northamptonshire cobrand.

2023-12-05 17:15 UTC, dracos commented on perllib/FixMyStreet/Cobrand/WestNorthants.pm
> +}
Ah yes, and I guess we'll be turning off/eventually removing that old cobrand sending reports/updates anyway (unless they have to be moved due to other message).

2023-12-05 17:15 UTC, dracos approved these changes
Thanks, hopefully nothing I suggested broke anything ;)

2023-12-06 10:18 UTC, merged