[FMS][Open311] Send images when comment on private report
mysociety/fixmystreet pull request #4766
Opened 2023-12-12 16:35 UTC by MorayMySoc

If an image is on a comment which was made on a private report Open311 can not download the image as it will not be visible.

In this case, send the photos directly to open311

Open311 end still to do

https://github.com/mysociety/societyworks/issues/3709

[skip changelog]

2023-12-13 09:56 UTC, dracos requested changes
It looks like open311-adapter Confirm and Alloy are the main ones that do something with a photo on an update. I assume we're not changing Confirm as part of this (not sure what it would do), so we only want this change for Alloy? So I guess I'm saying you need a different flag to check to do this direct attachment of photo in an update, where you know the other end can handle it. Your new `_add_photos_to_upload` isn't checking `upload_files` as `_populate_service_request_uploads` does, so it should probably be doing that, but also have a new flag upload_files_updates or something better, to check, and then can be added to Open311Alloy?

2023-12-15 10:00 UTC, MorayMySoc commented
I'm thinking that now, testing for `upload_files_for_updates` is tested before getting to` _add_photos_to_upload` so should be ok

2023-12-15 10:08 UTC, dracos approved these changes
Looks good, not sure why the extra image is present though is all.

2023-12-15 10:08 UTC, dracos commented on t/sample.jpg
Not sure why this has been added? :)

2024-01-02 12:24 UTC, merged

2024-01-02 12:39 UTC, MorayMySoc commented
Not merged as broke master so had to reset master