[FMS] Add a dropdown to the admin to change send_status
mysociety/fixmystreet pull request #4767
Opened 2023-12-13 17:33 UTC by MorayMySoc

If a report is marked as not sent can choose whether to set it as processed, unprocessed or skipped.

https://github.com/mysociety/fixmystreet/issues/3908

[skip changelog]

2023-12-15 11:17 UTC, dracos requested changes
Couple of small changes is all

2023-12-15 11:17 UTC, dracos commented on perllib/FixMyStreet/App/Controller/Admin/Reports.pm
> +            $c->forward('/auth/check_csrf_token');
This has already been checked above on line 296.

2023-12-15 11:17 UTC, dracos commented on templates/web/base/admin/reports/_edit_main.html
> +[% IF NOT problem.whensent %]
We probably want to restrict this to superusers, might be hard to explain otherwise.

2023-12-15 11:17 UTC, dracos commented on perllib/FixMyStreet/App/Controller/Admin/Reports.pm
> +            $c->forward( '/admin/log_edit', [ $id, 'problem', 'send_state_change'] );
Do we think this deserves a special log entry? I guess mark as sent/resend do, and it's not really an "edit" is it.

2023-12-15 16:27 UTC, MorayMySoc commented
I changed an `unlike` to `content_unlike` as well, as think that wasn't doing what I expected.

2023-12-20 15:52 UTC, dracos approved these changes

2023-12-20 16:13 UTC, merged