[TfL] Initialise single sign on
mysociety/fixmystreet pull request #4783
Opened 2024-01-08 11:43 UTC by MorayMySoc

Adding single sign on for TfL staff

2024-01-08 13:25 UTC, chrismytton requested changes
You'll need to add a `sub user_from_oidc` method in the cobrand to pull the appropriate fields out of the id_token that's returned.

When I did it for Camden I also added in some (temporary) logging so I could see the fields in the id_token, see https://github.com/mysociety/fixmystreet/pull/4170. Then in https://github.com/mysociety/fixmystreet/pull/4295 I updated it to use the correct fields and removed the temporary logging.

Regarding the server config, I think the `logout_uri` needs to be an Azure URL, which we then call to log the user out in Azure. This is the code that uses the `logout_uri` config:

https://github.com/mysociety/fixmystreet/blob/0eac24d8c4e6bce7d404b13d0f6b18e9a05b6563/perllib/FixMyStreet/App/Controller/Auth/Social.pm#L219-L225

2024-01-08 16:38 UTC, chrismytton approved these changes
Looks good! 👍

2024-01-08 16:38 UTC, chrismytton commented on perllib/FixMyStreet/Cobrand/TfL.pm
> +    my $email = $payload->{last_name};
Unlikely that the email is in the last_name field, but I guess doesn't really matter if you're coming back to change this anyway! 🙂

2024-03-15 09:30 UTC, chrismytton commented
@MorayMySoc Can this be closed now https://github.com/mysociety/fixmystreet/pull/4796 has been merged?

2024-03-15 09:34 UTC, MorayMySoc commented
As above - this will not be merged as was superseded by https://github.com/mysociety/fixmystreet/pull/4796

2024-03-15 09:34 UTC, closed without merging