[TfL] Users with TfL email not to be prompted to change password
mysociety/fixmystreet pull request #4806
Opened 2024-01-23 12:42 UTC by MorayMySoc

TfL Staff will be logging in by OIDC only so shouldn't be forced to update their FMS password

[skip changelog]

2024-01-23 12:43 UTC, MorayMySoc commented
Hopefully it's an obvious thing to reviewers, but the log in for the tests isn't working for me - something to do with tfl having an extra data password field - though seems to log in ok later on in another test. I've tried setting extra metadata, but either it's something else or I did that wrong. Pointers appreciated.

2024-01-23 17:05 UTC, dracos requested changes

2024-01-23 17:05 UTC, dracos commented on t/cobrand/tfl.t
> +    $tfl_staff->set_extra_metadata('last_password_change', time() - 200000);
You're not using tfl_staff here so no need to change and reset its last_password_change in this test.

2024-01-24 13:40 UTC, dracos approved these changes
📍

2024-01-24 15:25 UTC, merged