[TfL] Start pod documentation
mysociety/fixmystreet pull request #4812
Opened 2024-01-25 09:53 UTC by MorayMySoc

Beginning of pod documentation for TfL Cobrand

[skip changelog]

2024-01-25 12:41 UTC, dracos requested changes
Thanks for looking at this.
One suggestion - for the oneliners that are sort of configuration, some other cobrand files use a `=over 4` and interleaved `=item` rather than headings for each one, which might make sense for some of these? Can reorder the functions if that makes more sense too (either for short ones, or to group them more thematically if anything could be better elsewhere).

2024-06-12 10:54 UTC, MorayMySoc commented
I've tidied up pretty much where I was up to so hopefully tidier, but not complete.

2024-06-28 10:44 UTC, dracos reviewed
A number of suggestions, but I made them all whilst going through it, so if you'd like to look over and check you agree :)

2024-06-28 10:44 UTC, dracos commented on perllib/FixMyStreet/Cobrand/TfL.pm
> +=item * surrounding_boroughs
is called surrounding_london (as they're not boroughs surrounding)

2024-06-28 10:44 UTC, dracos commented on perllib/FixMyStreet/Cobrand/TfL.pm
> +This is initiated by an annual cron job
It runs more than annually :)

2024-06-28 10:44 UTC, dracos commented on perllib/FixMyStreet/Cobrand/TfL.pm
> +Reports are deleted from TfL after 7 years if they are not safety critical or after 3 years if they are
The reverse - safety ones are kept for 7

2024-06-28 11:04 UTC, MorayMySoc commented
Ok - thank you! Much more active voice too :-) I've added an extra fix-up that highlights account is created and role is assigned (which was the bit I missed out altogether), which I hope makes sense. But will try to follow this pattern with pod then

2024-06-28 11:20 UTC, merged