Added role button to span.report-a-problem-btn and "Current page" indicator to navbar
mysociety/fixmystreet pull request #4919
Opened 2024-04-11 13:50 UTC by lucascumsille

Fixes: https://github.com/mysociety/societyworks/issues/4257

- [ ] Added `role="button"` to `span.report-a-problem-btn` this should give context to screen readers about this element considering that pressing it takes you to the postcode input `#pc` in the homepage.
- [ ] I also added a `tabindex="0"` to make the `span.report-a-problem-btn` focusable with keyboard. We can drop this commit if we think is too redundant with the behaviour on `front.js`. I added it because it seemed confusing to have an element with `role="button"` that can't be focused.
- [ ] Added `<span>Current page</span>` inside `span` elements contained in `nav-menu nav-menu--main`. This will allow users using screen reader to know which page they currently are.

Let me know if you'd rather me to create a PR to put the "Current page" bit, considering it is not directly related with the issue.

[Skip changelog]

2024-04-22 16:14 UTC, dracos requested changes
Think something needs moving, and one text suggestion is all :)

2024-04-22 16:14 UTC, dracos commented on web/js/front.js
> +        lk.setAttribute('role', 'button');
This should I think be in the `if` statement above, not this one.

2024-04-22 16:14 UTC, dracos commented on templates/web/base/main_nav.html
> +            <span class="screen-reader-only">Current page</span>
Could it be `(current page)`, think for some reason it's just a bit better in brackets.

2024-04-22 16:14 UTC, dracos commented on web/js/front.js
> +        lk.setAttribute('tabindex', '0');
Again, think should be the `if` above.
I think keyboard focusable is fine, makes it more consistent with the mouse-based behaviour, doesn't it.

2024-04-23 11:47 UTC, lucascumsille commented
Thanks @dracos I added a fixup for each one. I'll squash `Role` and `Tabindex` into one if that's ok and leave the current page on its own before merging.

2024-04-30 06:44 UTC, merged