WIP Added btn--primary class to "Continue" button in New report page
mysociety/fixmystreet pull request #4943
Opened 2024-05-01 07:49 UTC by lucascumsille

Fixes: https://github.com/mysociety/societyworks/issues/4246

With this PR "Continue" button will have  same styling as `btn--primary`, to match the branding of each cobrand, the disabled state has also been updated so it has a more evident "disabled" state.

NOTE: To fix the original issue, including `btn-primary` is more of a bonus, but we could also get away with keeping what we currently have and add transparentize effect that passes the contrast colour to the disabled state. However this could be an opportunity to make a standard across all cobrands the use of the mixin `button-variant` for `btn--primary`.  As an extra I think we could also include an extra variable in the mixin to control the `border-radius` property. We would be covering more topics, so happy to open a new issue to update the "button-variant" if you think that would be better. 

@dracos before moving ahead I wanted to check if you are happy with this solution, because I'll need to include other commit to tidy up all the unnecessary uses of `btn-primary` `btn--primary` and include the `button-variant` mixin in all cobrands that are not using it.

### Default:
<img width="450" alt="Screenshot 2024-05-01 at 08 35 42" src="https://github.com/mysociety/fixmystreet/assets/13790153/fe533868-6a1a-42bd-8194-4e7fd8d12eb7">

### Disabled
<img width="450" alt="Screenshot 2024-05-01 at 08 36 28" src="https://github.com/mysociety/fixmystreet/assets/13790153/92e9f31a-1053-41f9-a0b8-52bbe44753e7">

2024-05-03 12:45 UTC, dracos reviewed
There are a lot of Continue buttons in this template, but you've only updated one of them, was that deliberate?
I guess it looks like the difference was the "Continue" button was steps *within* the process, and then the "Submit" at the end is already btn--primary as the final actual-submission step. But I guess that doesn't really matter/make any difference, if you think it makes more sense for them all to be the same, okay with me.
I don't know how many things would need tidying up, I wouldn't want this to become a giant thing, but as always if it ends up making things simpler for the future, is good.

2024-05-07 07:32 UTC, lucascumsille commented
> I guess it looks like the difference was the "Continue" button was steps within the process, and then the "Submit" at the end is already btn--primary as the final actual-submission step. But I guess that doesn't really matter/make any difference, if you think it makes more sense for them all to be the same, okay with me.

My thought was there is only one button visible at a time, so it didn't make much difference. With a "back" button right next to the "continue" one it would have more meaning to have a classic "primary" and "secondary" button approach.

>I don't know how many things would need tidying up, I wouldn't want this to become a giant thing, but as always if it ends up making things simpler for the future, is good.

I think I'm following the same approach we have been following over the last year or so, trying to standardised the branding process with new variables and reduce the need of overrides =)

2024-10-31 10:28 UTC, dracos requested changes
Couple of tiny comments is all

2024-11-04 11:43 UTC, dracos approved these changes
Thanks :)

2024-11-04 13:14 UTC, merged