Form error identification improvements
mysociety/fixmystreet pull request #5000
Opened 2024-06-11 10:29 UTC by lucascumsille

Fixes: https://github.com/mysociety/societyworks/issues/4217

- [ ] SW ref 39: Landing page
In Firefox, the error message remains in the same place when the page is scrolled, so you lose the visual relationship between it and the form field that is in error. Use a text error message, as has been done on other pages.
- [ ] SW ref 40: Local RSS feeds and email alerts
If the input is left empty, no error message is provided.
- [ ] SW ref 41:  Local RSS feeds and email alerts - part 2
An error message is provided in text, but it is not programmatically associated with the email address input element.

[Skip changelog]

2024-06-12 08:39 UTC, lucascumsille commented
@dracos This PR is not ready, but I left a comment for the third point, which I'm not sure how to tackle:
>SW ref 41: Local RSS feeds and email alerts - part 2

thanks =)

2024-06-12 12:03 UTC, dracos requested changes

2024-06-17 07:07 UTC, lucascumsille commented on templates/web/base/around/postcode_form.html
> +            [% END %]
I added it because I thought it makes the error more obvious.

2024-06-17 07:15 UTC, lucascumsille commented on templates/web/fixmystreet.com/around/location_error.html
> -
Good one. I added a commit fixup, reverting that change.

2024-06-17 07:50 UTC, lucascumsille commented
@lizettal 
SW ref 41: Local RSS feeds and email alerts - part 2
Will be covered by:
https://github.com/mysociety/fixmystreet/pull/4952

2024-06-17 07:52 UTC, lucascumsille commented
@dracos thanks for clarifying all the above, about the Firefox bit I agree, let's leave as it is. I'll move SW 41 to this PR:
https://github.com/mysociety/fixmystreet/pull/4952

2024-06-17 08:28 UTC, dracos approved these changes
Couple of typos in the commit messages is all :)

2024-06-17 08:37 UTC, merged