[Brent] [Waste] Add garden subscription notice.
mysociety/fixmystreet pull request #5013
Opened 2024-06-17 15:41 UTC by neprune

[skip changelog]

https://mysocietysupport.freshdesk.com/a/tickets/4187

<img width="1097" alt="brent subscription text" src="https://github.com/mysociety/fixmystreet/assets/9289297/31cf38ec-9703-4248-84cf-e9a1e3f985e9">

2024-06-18 08:02 UTC, dracos requested changes
If they're already subscribed, there's no way they could view this page, which is the intro page for someone who doesn't have a subscription :)
They didn't say where they wanted this, but from what I read I thought they wanted it on the bin day page - where if you're staff it prints out "Modify your garden subscription" it would have the text there, alongside their garden waste subscription information. 

Given they must already have a sub to view that, the text could be "If you are looking to add another service, please contact our customer services team on 020 8937 5050 who will be able to do this for you."

2024-06-18 08:22 UTC, neprune commented
> If they're already subscribed, there's no way they could view this page, which is the intro page for someone who doesn't have a subscription :) They didn't say where they wanted this, but from what I read I thought they wanted it on the bin day page - where if you're staff it prints out "Modify your garden subscription" it would have the text there, alongside their garden waste subscription information.
> 
> Given they must already have a sub to view that, the text could be "If you are looking to add another service, please contact our customer services team on 020 8937 5050 who will be able to do this for you."

Well that makes sense 😅 . Thanks 🙏

2024-06-18 14:50 UTC, neprune commented
![demo screenshot](https://github.com/mysociety/fixmystreet/assets/9289297/b7465c52-961a-4139-ad84-fbf311060563)

2024-06-19 09:46 UTC, dracos requested changes
Sorry, afraid this still won't appear where you want it to

2024-06-19 09:46 UTC, dracos commented on templates/web/base/waste/services.html
> +                  If you already have an active Garden Waste subscription and are looking to add another service, please contact our customer services team on 020 8937 5050 who will be able to do thi
To get here, you must have a subscription, so the first part of this If isn't needed, can just be "If you are looking to add..."

2024-06-19 09:46 UTC, dracos commented on templates/web/base/waste/services.html
> +            [% IF c.cobrand.moniker == 'brent' %]
This is only reached if `show_garden_modify` is true, which for Brent is only for staff (that's why we want to show this message), so this isn't shown to normal users (see normal user display attached). So it needs to be its own section, presumably can still be inside the `NOT pending_cancellation` section, but outside this section.

<img width="765" alt="image" src="https://github.com/mysociety/fixmystreet/assets/154364/9dc97ad4-2988-4308-b255-292bf876688c">

2024-06-19 10:28 UTC, neprune commented
@dracos sorry, not my brightest moment, have changed to appear for non-staff

2024-06-19 11:50 UTC, dracos approved these changes
Looks good, thanks :)

2024-06-25 10:44 UTC, merged