[Merton] Styling amendments
mysociety/fixmystreet pull request #5021
Opened 2024-06-20 07:21 UTC by lucascumsille

Fixes: https://github.com/mysociety/societyworks/issues/4381

For reviewing and in case of feedback I have added a commit for each point, but once the PR is ready I'll rebase and squash everything into one commit.

[skip changelog]

2024-06-20 07:24 UTC, lucascumsille commented
@jacquelinebylau just in case I have this PR ready, I have asked the developers who should be reviewing it.

2024-06-20 20:00 UTC, dracos requested changes
Looks very good, a few small issues is all

2024-06-20 20:00 UTC, dracos commented on web/cobrands/merton/base.scss
> +        color: $merton-dark-green;
This is causing a bug in the mobile nav when you hover over, you get dark green on grey, rather than white on grey as you get on unvisited links.

2024-06-21 09:12 UTC, dracos commented on web/cobrands/merton/base.scss
> +        color: $merton-dark-green;
Also this only changes it for visited, not all links as they asked in B16.

2024-06-21 09:14 UTC, dracos commented on web/cobrands/merton/base.scss
> +    overflow: visible;
Was in their styling, will just leave for now

2024-06-21 09:14 UTC, merged