Added tabindex to .js-recentre-map element
mysociety/fixmystreet pull request #5120
Opened 2024-08-19 08:38 UTC by lucascumsille

Fixes: https://github.com/mysociety/societyworks/issues/4488

Currently `.js-recentre-map` is the only control element in the map that can't be focused. By adding a `tabindex="0"` we allow keyboard users to be able to use that element.

Preview here:

https://github.com/user-attachments/assets/4efb1a2b-d266-4915-bf83-fcc6c77bf82a

[Skip changelog]

2024-08-22 21:03 UTC, davea requested changes
For me on macOS Safari the "Aerial map" and "Hide pins" buttons aren't focusable:

![tabindex](https://github.com/user-attachments/assets/a0c0e509-5487-4696-9b6a-b5eca95b2253)


Strangely, adding a `tabindex` to the `a` elements for those buttons doesn't make them focusable...

2024-08-26 07:12 UTC, lucascumsille commented
@davea can you double check if the element has the tabindex, I just tested on safari an it's working for me.

https://github.com/user-attachments/assets/eab68000-230b-489c-af5f-c9d10eab3bd2

2024-08-28 16:55 UTC, lizettal commented
I think this got resolved on our call earlier but @lucascumsille @davea can you please update accordingly

2024-08-29 06:16 UTC, lucascumsille commented
I think it should be ready, but @davea let me know if you think I need to change something

2024-08-29 10:37 UTC, davea commented
Yep, resolved. This was because I didn't have the relevant "Press Tab to highlight each item on a web page" option turned on in Safari.

2024-08-29 10:37 UTC, davea approved these changes

2024-08-29 10:42 UTC, merged