[Bexley][WW] Only skip parent addresses if they are marked as 'shell' properties
mysociety/fixmystreet pull request #5203
Opened 2024-10-03 12:06 UTC by nephila-nacrea

We were skipping over all parent addresses on the assumption that all were 'shell' addresses that shouldn't be displayed. But the 'shell' status only applies to some parents.

For https://mysocietysupport.freshdesk.com/a/tickets/4432.
Closes https://github.com/mysociety/societyworks/issues/4498.

[skip changelog]

2024-10-03 17:21 UTC, nephila-nacrea commented on bin/bexley/make-bexley-ww-postcode-db
> -# It is possible for UPRNs in child_uprns to not occur in the postcodes table
Turns out that the P/PP check fixes this issue as well, so have deleted this portion.

2024-10-04 09:13 UTC, dracos requested changes
One tiny change, good to get rid of the unneeded table; could you split it into two commits, one that changes to use the parent flag and removes the child_uprns table, and then one that ignores P/PP? :)

2024-10-04 09:13 UTC, dracos commented on bin/bexley/make-bexley-ww-postcode-db
> +        next if $blpu_class && ( $blpu_class eq 'P' || $blpu_class eq 'PP' );
Doesn't need the first if I think, given you've made sure it's not undefined in the line before.

2024-10-07 09:11 UTC, dracos approved these changes
📮

2024-10-18 09:58 UTC, merged