[Bexley][WW] Display links for new container & removal requests
mysociety/fixmystreet pull request #5217
Opened 2024-10-09 22:09 UTC by nephila-nacrea

Currently placeholder links.

For https://github.com/mysociety/societyworks/issues/4570.

[skip changelog]

2024-10-22 16:54 UTC, chrismytton requested changes
This looks great so far! The controller code all looks good, from what I can tell. Just one suggestion about the tests.

2024-10-22 16:54 UTC, chrismytton commented on t/app/controller/waste_bexley_container_requests.t
With these tests I think we ideally want integration tests, i.e. ones that make GET requests to web endpoints, rather than unit tests like these that test the implementation of a individual methods.

Obviously a lot of stuff won't work properly at this point! But I think integration tests provide more comprehensive testing of the user interaction, and are generally a bit easier to maintain as they don't rely as much on the underlying implementation.

If you `git grep "subtest 'Request"` there are various existing tests that can hopefully be copied and tweaked a bit.

2024-10-23 08:45 UTC, nephila-nacrea commented on t/app/controller/waste_bexley_container_requests.t
I am adding integration tests as part of https://github.com/mysociety/fixmystreet/pull/5219 . Not sure if it would make things complicated by trying to add the beginning of one here and rebasing 🤔 
I like having both these unit-type tests and the more complex integration tests. In this case, I wanted an easy way of checking that my data munging was correct for _set_request_containers(), as there's a lot going on in that one sub, and didn't want other code getting in the way.
What are your thoughts?

2024-10-23 11:00 UTC, nephila-nacrea commented on t/app/controller/waste_bexley_container_requests.t
Having said all that...I have a bug that would be better (thematically) to fix in this PR, so I think I'll try to add & push an integration test for that.

2024-10-24 14:54 UTC, chrismytton commented on t/app/controller/waste_bexley_container_requests.t
That all sounds sensible to me 🙂

2024-10-24 14:55 UTC, chrismytton approved these changes

2024-10-28 10:55 UTC, merged