[Merton] Bin not being returned correctly and waste spillage
mysociety/fixmystreet pull request #5252
Opened 2024-11-12 10:47 UTC by MorayMySoc

Part 1 of MRT167 Set up remaining processes in WW

Allow residents to select specified bin types to report a problem that bins haven't been returned correctly to the correct  location or have been left open.

These reports allow a request for the bin collectors to return and rectify the issue along with a notes field

Waste spillage can be reported just with a notes field.

Category details on servers with same branch name.

https://github.com/mysociety/societyworks/issues/4593

Please check the following:

- [ ] Has the code POD documentation been added or updated?
- [ ] Whether this PR should include changes to any public documentation, or the FAQ;
- [ ] All cobrand-specific commits start their commit message with the cobrand in square brackets;
- [ ] Is new functionality tested? CodeCov will warn you about the diff coverage, but won’t complain about e.g. new files;
- [ ] Will cobrand-specific changes require additional work to ensure consistent behaviour on www.fixmystreet.com? 
- [ ] Are the changes tested for accessibility?
- [ ] Have you updated the changelog? If this is not necessary, put square brackets around this: skip changelog

Please check the contributing docs, and describe your pull request here.
Screenshots or GIF animations (using e.g. LICEcap) may be helpful.

Please include any issues that are fixed, using "fixes" or "closes" so that
they are auto-closed when the PR is merged.

Thanks for contributing!

2024-11-12 11:37 UTC, dracos requested changes
Looks good, just a few small things :)

2024-11-12 11:37 UTC, dracos commented on templates/web/merton/waste/enquiry-problem.html
> +service = services.$service_id;
These values aren't used; think these come from Bromley version, but e.g. Borsetshire's is a bit simpler, you don't need to construct an `f`, you could only have:
```
[% PROCESS waste/enquiry.html
    title = 'Report a problem'
    field_options = [
        { value = 'Bin not returned', label = 'Bin not returned correctly' },
        { value = 'Waste spillage', label = 'Waste spillage' },
    ]
%]
```

2024-11-12 11:37 UTC, dracos commented on t/app/controller/waste_merton.t
> +    subtest 'test report a problem' => sub {
Probably worth a little test for the Waste spillage as well.

2024-11-12 11:37 UTC, dracos commented on templates/web/base/waste/services.html
> +    [% IF c.cobrand.waste_report_problem(unit.service_id) %]
I think perhaps for now we just do NOT unit.orange_bag, no need for special sub-check. It's unclear from 'recycling' in their original message if that includes paper and card, but I don't see why it wouldn't, they could go missing also, might as well have everything to begin with.

2024-11-12 13:01 UTC, MorayMySoc commented
Forgot to say, config is in same branch on servers...

2024-11-19 10:25 UTC, dracos approved these changes

2024-12-11 11:20 UTC, merged