[Merton] Adds parks and open spaces layer
mysociety/fixmystreet pull request #5294
Opened 2024-12-06 17:02 UTC by MorayMySoc

Layer contains parks that Merton not responsible for:
    Wimbledon Common, Mitcham Common, Morden Hall Park
    which have specific stoppers to guide to the right
    place.
    
    Only allowed to make a park report on a park or open
    space on the layer for responsible parks.
    
    Exceptional park Commons Extension Sports Ground is
    in Kingston, but is responsibility of Merton so
    can be selected from Merton Cobrand.

   And Cypress tests.
    
    https://github.com/mysociety/societyworks/issues/4643
    https://mysocietysupport.freshdesk.com/a/tickets/3934

[skip changelog]

2024-12-13 12:08 UTC, dracos requested changes
Looking good, and thanks for the tests, but I don't think the out-of-boundary park  works on .com, there's nothing to set that up to work (sorry if I missed it!).

2024-12-16 17:20 UTC, MorayMySoc commented on templates/web/merton/report/new/roads_message.html
> +            To report an issue at <b>Mitcham Common</b>, please contact <a href=http://mitchamcommon.org/contact-us>Mitcham Common Conservators</a> who own and manage it.
Sorry!

2024-12-17 10:16 UTC, dracos commented on templates/web/fixmystreet.com/report/new/roads_message.html
> +    <div id="js-not-a-park" class="hidden js-responsibility-message js-parks-merton">
Could js-not-a-park be js-not-a-merton-park just to be clear?

2024-12-18 15:28 UTC, dracos commented on web/cobrands/fixmystreet-uk-councils/assets.js
> +    fixmystreet.message_controller.road_not_found(layer);
@MorayMySoc I think this needs a return true function, in order to kick in when the parent category is picked, before the sub category.

2024-12-18 17:16 UTC, dracos approved these changes

2025-01-05 22:55 UTC, merged